### ISSUE TITLE
Improve Lighthouse scores on website

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#103]
_Update: mostly improved now, see 7/27 comment below_

While I'm not inclined to go nuts getting to 100 on all the scores, I *was* pretty happy with 90+ numbers when the Bridgetown site first launched, and now our scores suck in large part because I was a bozo and added a YouTube video embed directly on the homepage.

Anyway, this is a general issue to take another look and see if we can improve things. I also noticed the Inter font files are pretty large so maybe we can optimize that as well.

**Comment by andrewmcodes** [comment]
Peaked my interest so I took a look and I could bump most of these but there will be tradeoffs to the design for some that you'll have to decide the importance of. The font is definitely the killer for performance. Lots of interesting research out there on how to get some gains here.

### Desktop

![image](https://user-images.githubusercontent.com/18423853/88144625-3cf76c80-cbc7-11ea-9316-e6592aee2cc6.png)

### Mobile

![image](https://user-images.githubusercontent.com/18423853/88144694-5698b400-cbc7-11ea-88e9-31155b40ca3a.png)

## Quick Wins

Best practices would be easy to get to 100. `Add 'rel="noopener"' or 'rel="noreferrer"' to any external links to improve performance and prevent security vulnerabilities.`

SEO to 100 seems easy enough without compromising the style. Its upset about a few links in the footer which doesn't make a ton of sense to me but w/e. 

Accessibility will be the hardest imo - if you aren't building for it out of the gate, it can be hard to add in retroactively. Especially the sequential ordering of heading elements. Font seems to be the biggest drain on the perf which wouldn't be hard to solve but may be hard to do well. 

Lmk if you want to talk more about this! Web perf is definitely interesting to me. Ping me on discord bc I am a bit slow to respond on GH :shrug:

**Comment by MikeRogers0** [comment]
I opened up a few PRs so you can pick and choose the performance changes you like 👍 

For the fonts:

1. It looks like you're pulling all of fonts from https://github.com/ForkAwesome/Fork-Awesome (~100kb or so) but only using a handful of them. I'd suggest https://feathericons.com/ as an alternative & going SVG for all of them if that's something you're interested in?
2. The `Inter` font is pretty heavy, do you know why you picked it?

**Comment by jaredcwhite** [comment]
Thanks @andrewmcodes & @MikeRogers0 

1. Def interested in streamlining icon usage, I don't think we're actually using very many anyway.
2. I'd like to stick with Inter, it's subtly different from default fonts even considering San Francisco on Mac/iOS which is probably the most similar.

**Comment by jaredcwhite** [comment]
Whatever the latest tweaks were, seems like we're getting top-notch Desktop scores now:

<img width="525" alt="Screen Shot 2020-07-27 at 12 13 02 PM" src="https://user-images.githubusercontent.com/658496/88581860-a251c000-d002-11ea-98d6-2b1d19f16615.png">

Mobile is still lacking on the Performance metric but some of the results seem odd, like a 7.7s Time to Interactive which doesn't sound right to me. (At least I haven't noticed any sluggish behavior on mobile vs. desktop in practice.) Will need to investigate further. But for now, I think this is fairly low priority.

**Comment by andrewmcodes** [comment]
I may have a solution to drastically increase font loading. When I get some time I'll try it out on the btown site and report whatever happens.

**Comment by MikeRogers0** [comment]
![image](https://user-images.githubusercontent.com/325384/98358576-d5064e00-201e-11eb-9374-e9e975863ca6.png)
![image](https://user-images.githubusercontent.com/325384/98358597-ddf71f80-201e-11eb-88c8-7de4b4c703d2.png)

I was thinking add about adding [resource hints (using the HTTP headers)](https://www.w3.org/TR/resource-hints/#fetching-the-resource-hint-link) / switching out the icons for SVGs.

**Comment by jaredcwhite** [comment]
I'm not entirely sure I believe Lighthouse scores at this point.￼￼ 😋 We might already be at the point of diminishing returns—but if you want to try some more tweaks, more power to ya!

**Comment by andrewmcodes** [comment]
I've been meaning to do this but one issue is likely the purge plugin being used is not the correct one.

**Comment by andrewmcodes** [comment]
The rest of these are just webpack config related.
