### ISSUE TITLE
docs: Add Vercel to the Deployment page

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#104]
Definitely should include them alongside Netlify… also I'm not sure Aerobatic is that great of a recommendation anymore…

**Comment by wout** [comment]
Just chiming in here, I'm running my own Dokku server and would love to see how it's done with Herokuish deployments. I don't have a lot of experience with SSG's, so I'm wondering if the site is generated locally and shipped as a static package or built at deployment on the server. I wouldn't mind compiling a step-by-step guide including gotcha's and caveats if someone can point me in the right direction.
