### ISSUE TITLE
feat: Allow custom permalink style assignable by defaults

### ISSUE THREAD

**Issue by jamie** [bridgetownrb/bridgetown#116]
## Summary

I want to use `defaults` to set a permalink format across multiple pages.

## Motivation

I'm pulling a directory of markdown files generated by another tool, which doesn't provide a large amount of access to YAML frontmatter. I would like to generally use `permalink: pretty` as a sitewide config, but use a different permalink style for files from this other tool.

## Reference-level explanation

Ideally, I would like to do something like this:

```
defaults:
  - scope:
      path: notes/
    values:
      template: /:path/:basename:output_ext
```

However, [`Bridgetown::Page#template`](https://github.com/bridgetownrb/bridgetown/blob/main/bridgetown-core/lib/bridgetown-core/page.rb#L96-L107) only seems to be checking the sitewide configuration.

I can get it to work locally by changing the method to:

```
    def template
      if !html?
        "/:path/:basename:output_ext"
      elsif data["template"]
        data["template"]
      elsif index?
        "/:path/"
      else
        Utils.add_permalink_suffix("/:path/:basename", site.permalink_style)
      end
    end
```

## Unresolved Questions

Before I PR-ify this, `template` isn't referenced terminology in the [docs](https://www.bridgetownrb.com/docs/variables) so I'd love some input on a better naming option.

[style_to_permalink](https://github.com/bridgetownrb/bridgetown/blob/2486c19e82e1f7b5e0185a037b5970552a60ef67/bridgetown-core/lib/bridgetown-core/configuration.rb#L283-L302) has a number of meta-styles, if we're going to pull in from page data it'd be nice if we also were able to use those here. In which case, that method should probably be moved to Utils so it's better-available.

Also, checking if that's a good place to expand the placeholder list - it'd be nice if we had title/slug/categories available from [the list in the docs](https://www.bridgetownrb.com/docs/structure/permalinks#placeholders). These would augment Page#url_placeholders.

**Comment by jaredcwhite** [comment]
Thanks @jamie, I'll need to dig into this a little further as I'm fuzzy what the template value for pages does per se, but I also see this as related to the work we should do for #50, so maybe we can wrap general permalink improvements into that.

**Comment by jaredcwhite** [comment]
@jamie I think the new data cascade functionality in 0.17 would help you with this, as you could easily set different `permalink` templates for different folders. I'll close this issue for now but if you run into any problems feel free to comment.
