### ISSUE TITLE
docs: clarify location of static assets / media

### ISSUE THREAD

**Issue by julianrubisch** [bridgetownrb/bridgetown#117]
## Motivation

Creating my first bridgetown site, I couldn’t make out the proper location for static assets (images, other media). This resulted in unforeseen errors like `url()` s not working in SCSS etc.

Only after try and error I found out that they have to live in `src`.

## Suggestion

I looked at https://www.bridgetownrb.com/docs/static_files and https://www.bridgetownrb.com/docs/frontend-assets and didn’t find what I was looking for. Only after re-reading the Core Concepts I found a lead... Maybe it’d be better to make the menu items clearer and creating a separate one for media

**Comment by jaredcwhite** [comment]
Thanks @julianrubisch, we should definitely improve the docs on this as it's unclear if images/etc. should live in the `frontend` tree or `src` tree and we don't yet have Webpack support per-se for fingerprinting images.
