### ISSUE TITLE
Pages in sub folders not generated as expected

### ISSUE THREAD

**Issue by DEfusion** [bridgetownrb/bridgetown#120]
Pages are not generated [to the output as specified in the documentation](https://www.bridgetownrb.com/docs/pages).

**Bridgetown Version**: 0.16.0 "Crystal Springs"

**To Reproduce**

- `bridgetown new test`
- create a page at `test/foo/bar.md` with front matter:
```
---
layout: page
title: Bar
---
```
- `yarn build`

**Current behavior**
This will output the file to `output/foo/bar/index.html`, adding more pages to this directory follows that pattern i.e. `fizz.md` > `output/foo/fizz/index.html` etc.

**Expected behavior**
It should output the file to `output/foo/bar.html`.

**Computing environment (please complete the following information):**
 - OS: OS X
 - Ruby Version: 2.6.6

**Comment by jaredcwhite** [comment]
@DEfusion It's probably a discrepancy between the examples in the Pages documentation and the `pretty` permalink style. You can change the setting (perhaps use `date`) to get the behavior you want…see here: https://www.bridgetownrb.com/docs/structure/permalinks#built-in-formats

**Comment by DEfusion** [comment]
Thanks @jaredcwhite it was set as the default `pretty` value, it's not quite clear from the permalinks docs whether that's the intended behaviour for pages when set to `pretty`. Switching it to `none` worked for me and is fine as my use won't have any posts.
