### ISSUE TITLE
feat: Make reading_time a first class citizen

### ISSUE THREAD

**Issue by julianrubisch** [bridgetownrb/bridgetown#129]
## Summary

Provide a `reading_time` liquid filter (https://www.bridgetownrb.com/docs/liquid/filters)

## Motivation

Reading time is nowadays displayed for most blog sites out there. One could argue that this should be made a plugin (maybe?), but according to the "backpack analogy", I was thinking, maybe this could be provided out of the box.

Feel free to close if this is out of scope :-)

**Comment by jaredcwhite** [comment]
@julianrubisch I'm cool with it if there's a generally agreed-upon standard for measuring words * time. Obviously different people have widely-varying reading speeds, plus different languages will vary as well. If we can take advantage of prior art here, that'd be great.

**Comment by julianrubisch** [comment]
Most Jekyll plugins allow to configure words per minute. I’ve read 180 and 200 as a reference count
