### ISSUE TITLE
Favicon Error shown on generated build

### ISSUE THREAD

**Issue by jaredmoody** [bridgetownrb/bridgetown#13]
After running `bridgetown new mysite` and building/serving, the following error is shown in the terminal:

```
ERROR `/favicon.ico' not found
```

Might be nice to either provide a blank favicon.ico out of the box or work around this error.

**Comment by jaredcwhite** [comment]
Thanks @jaredmoody! That'd be a much better experience. Will do. 👍

**Comment by jaredcwhite** [comment]
@jaredmoody actually……if you wanna do me a solid, add a blank favicon and submit a PR. Gotta get in that open source flow. 😁

**Comment by jaredcwhite** [comment]
@jaredmoody bump :)

**Comment by jaredcwhite** [comment]
Fixed with #32
