### ISSUE TITLE
feat: Allow no layout when a default layout is defined

### ISSUE THREAD

**Issue by wout** [bridgetownrb/bridgetown#159]
## Summary

When using a default layout, there should be a way to define "no layout".

## Reference-level explanation

We're using a default global layout with the following configuration:

```yml
-
    scope:
      path: ""
    values:
      layout: "default"
``` 

That's great because it eliminates the need to define the same layout everywhere. But there are some edge cases where no layout is required at all. For example, an RSS feed or a sitemap. We now have two workarounds. One is a layout called `feed.liquid` with just the following contents:

```liquid
{{ content }}
```

Another is to have `layout: false` in the front matter. Although, the latter adds the following warning to the logs:

```
[Bridgetown]      Build Warning: Layout 'false' requested in sitemap.xml does not exist.
```

So it's a hack, really.

## Solution

Both options work, but allowing to configure `layout: false` in the front matter solves the issue.

**Comment by ParamagicDev** [comment]
Out of curiosity, what warnings do you get with `layout: null`

Jekyll issues seems to say `layout: null` is the preferred syntax.

https://github.com/jekyll/jekyll/issues/2730

**Comment by wout** [comment]
The result:

![image](https://user-images.githubusercontent.com/107324/94998227-29458a80-05a8-11eb-803a-e1723bfa02cb.png)

I think because it considers `false` as a layout (e.g. `false.liquid`) and `none` as "no layout defined", so it uses the default.

**Comment by jaredcwhite** [comment]
I'm thinking `layout: none` is supported but I should test this out a bit more.

**Comment by wout** [comment]
Just checked and it is. Thanks!
