### ISSUE TITLE
feat: tags and categories for pages & collections

### ISSUE THREAD

**Issue by noraj** [bridgetownrb/bridgetown#161]
## Summary

There are [Predefined Variables for Posts](https://www.bridgetownrb.com/docs/front-matter#predefined-variables-for-posts) that are not available for pages like tags and categories.

## Motivation

Be able to create a `doc` layout based on `page` layout and have a documentation with tags enabled like for Mozilla, Joomla or Docker documentation (see https://github.com/mkdocs/mkdocs/issues/1828#issuecomment-515010657).

See an example of use case in the [Why this would be a great feature? of this issue](https://github.com/mkdocs/mkdocs/issues/1828) and [this comment example with screenshots](https://github.com/pmarsceill/just-the-docs/issues/255#issuecomment-622465275).

## Guide-level explanation

For all staticgen either there is no tags support at all or tags are available on for posts, I never have seen one yet that have tags support for pages. Here if post already have this feature it's like for Hexo, it shouldn't be difficult to enable those for pages too.

## Reference-level explanation

Copy the tags & categories features from post layout to page layout.

## Drawbacks

I see no reason to not doing it.

## Related issue

- https://github.com/hexojs/hexo/issues/1067#issuecomment-570943547
- https://github.com/pmarsceill/just-the-docs/issues/255
- https://github.com/mkdocs/mkdocs/issues/1828

**Comment by jaredcwhite** [comment]
Thanks @noraj for posting this. I think an similar problem along these lines is categories/tags don't get picked up from custom collections either. Only posts are privileged content. But…why? 🤔

**Comment by jaredcwhite** [comment]
We're going to support this eventually, but after further research it's definitely a non-trivial issue that exposes some of the weakness we inherited from our parent project (Jekyll) with regard to a robust taxonomy system.￼ Gotta say I'm inclined to put in the extra effort to "get this right" and not just tweak things piecemeal. Stay tuned…

**Comment by noraj** [comment]
Yeah I heard of Jekyll tags system that is not automatic and force you to create a yml file with a whitelist of terms.

**Comment by jaredcwhite** [comment]
@noraj Well it's not quite that bad 🙃… it does pick up tags automatically from front matter, but only from blog posts. That's it…no support for pages or custom collections.

**Comment by jaredcwhite** [comment]
Will be addressed by #187, closing
