### ISSUE TITLE
feat: Email obfuscation

### ISSUE THREAD

**Issue by julianrubisch** [bridgetownrb/bridgetown#166]
## Summary

Provide a liquid filter for obfuscation of email addresses (and possibly other types of contacts)

## Motivation

I'm creating a bridgetown site for a client and wanted to obfuscate email-addresses and phone numbers on the page

## Reference-level explanation

I took [react-obfuscate](https://github.com/coston/react-obfuscate/blob/master/src/obfuscate.js) as a reference and threw together the most basic liquid filter:

```ruby
class Filters < SiteBuilder
  def build
    liquid_filter "obfuscate_mail" do |input|
      output = "<a href=\"obfuscated\" "
      output += "style=\"unicode-bidi: bidi-override; direction: rtl\" "
      output += "onfocus=\"this.href = 'mailto:#{input}'\" "
      output += "onmouseover=\"this.href = 'mailto:#{input}'\">"
      output += "<script type=\"text/javascript\">document.write(\"#{input}\".split('').reverse().join('').replace('(', ')').replace(')', '('));</script></a>"
      output
    end
  end
end
```

If this addition is welcome, I can put up a PR in no time.

## Unresolved questions

- as of now, I only obfuscate email addresses. with a second parameter, the prefix (`mailto:`) should be easily configurable.

**Comment by jaredcwhite** [comment]
Good idea! Looking forward to your PR.
