### ISSUE TITLE
feat: Add or Document search capabilities

### ISSUE THREAD

**Issue by westonganger** [bridgetownrb/bridgetown#17]
Is it possible that bridgetown could implement or document some sort of basic search capability. I feel this is a very critical aspect of websites that is often overlooked by static site generators.

**Comment by jaredcwhite** [comment]
That would be super useful, for sure. In the past I used a customized version of a plugin for Jekyll that used a JS package that could search tokens generated in a JSON at build time. I should see if we can implement something similar, perhaps as an officially-sanctioned Bridgetown plugin.

**Comment by westonganger** [comment]
Great sounds good. If implmented as a plugin, I would also like to see a page about it directly in the main docs.

**Comment by jaredcwhite** [comment]
Making a note here we'll likely base a solution off of: https://lunrjs.com

It's worked well for me in the past and other plugins in the Jekyll world have utilized it…

**Comment by jaredcwhite** [comment]
![image](https://user-images.githubusercontent.com/658496/83283879-c58df980-a190-11ea-9bf0-6b3aebc47fd6.png)

It has begun!

**Comment by jaredcwhite** [comment]
Check out the search working now on the beta website! Plugin will be widely available when 0.15 is officially released:

https://beta.bridgetownrb.com

**Comment by jaredcwhite** [comment]
This plugin is now out in the wild alongside the release of Bridgetown 0.15!


https://github.com/bridgetownrb/bridgetown-quick-search

Wondering how I could fit in a mention of this into the docs somewhere…

**Comment by jaredcwhite** [comment]
_Finally_. 🤯
https://www.bridgetownrb.com/docs/core-concepts#adding-extra-features-to-your-site
