### ISSUE TITLE
Remove PageWithoutAFile in 0.20

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#179]
Whatever this class does that's different from Page isn't worth having a separate class for. It's not even used within the Bridgetown codebase itself…I think maybe a plugin or two use it and that's it. Let's just make it so Page serves the same purpose and ditch this badly-named subclass. 🙃

**Comment by jaredcwhite** [comment]
Already removed it in a WIP PR and the feed plugin uses its own similarly-named class (!!), so I think we can just say bye-bye.

**Comment by jaredcwhite** [comment]
Added a deprecation warning in 0.19, as I don't have time to track down testing edge cases for this release.

**Comment by ayushn21** [comment]
I found a use of this class in the `jekyll-sitemap` plugin. I was just trying to port it over to a Bridgetown plugin and it's used to create and add `sitemap.xml` and `robots.txt` to the site.

Easy enough to work around but I think I'll wait for your big content-realignment refactoring job before I complete the port so I can use the shiny new `Resource` classes :D

**Comment by jaredcwhite** [comment]
Yeah I forget which but another Jekyll plugin I looked at had *its own PageWithoutAFile* class instead of using Jekyll's (maybe for backwards compatibility??) so the whole setup is goofy. I hope to get to refactoring `Page` into something like `GeneratedPage` soon and then it can be a reliable substrate for all Bridgetown plugins going forward.

**Comment by jaredcwhite** [comment]
Resolved in 0.20.
