### ISSUE TITLE
The :title placeholder for permalinks isn't really the Title variable, it's the filename (or Slug variable)

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#194]
This somewhat related to #187 and is yet another head-scratcher we inherited when we forked.

If you look at the available placeholders for permalinks, you'll see that `:title` gets used a lot. That's usually how the filename gets inserted into the final URL.

_However_, if take a closer look at how that works, it quickly becomes apparently that the page's `title` front matter variable isn't used at all for the `:title` permalink placeholder. It's instead derived from either the page's filename itself, or alternatively the `slug` front matter variable (if present).

Huh? 🤨

If you instead use `:slug` itself as a placeholder, _the behavior at the letter case/ASCII level of how that slug value gets "slugified" to the output URL is different_ than when you use `:title`. Say what now? 🧐

One other issue (perhaps a separate issue)—the logic that converts permalink placeholders to their actual values lives inside of a…🥁…Liquid Drop.

😭

Plus users can't customize which permalink placeholder values are even available at all. Eleventy allows you to put template logic **inside** the permalink front matter so you can pull data in and manipulate it. We could probably do something similar with Ruby Front Matter but that is non-obvious.

Unfortunately, changing/refactoring any of this is likely to break any existing Bridgetown site, which is probably why Jekyll never improved their permalink system.

So I'm not sure what the best course of action is here, other than to say we should put some effort into investigating how we could make this better.

**Comment by andrewmcodes** [comment]
Could it possibly be put inside a plugin with the intent to merge for 1.0?

**Comment by jaredcwhite** [comment]
I like that idea!

**Comment by jaredcwhite** [comment]
Backtracking on that a smidge — I think what I may aim for is allowing the "content engine" to be configurable for a while. Something like `content_engine: legacy` by default, but folks can opt-in with `content_engine: resource`. We'll support the old page/document/permalink/etc. codepath for a while, with a deprecation warning to upgrade to the new Resource-based engine which will only be supported once we reach 1.0.

**Comment by jaredcwhite** [comment]
Permalink handling (and switch from `:title` to `:slug`) now totally overhauled for Resource engine in v0.20.
