### ISSUE TITLE
question: creating new GitHub topic

### ISSUE THREAD

**Issue by andrewmcodes** [bridgetownrb/bridgetown#196]
@jaredcwhite 

I'm going to open a PR to GitHub to curate the bridgetown topic and wanted to get your review first:

```md
---
aliases: bridgetownrb
created_by: Jared White
display_name: Bridgetown
github_url: https://github.com/bridgetown
logo: https://avatars1.githubusercontent.com/u/63275815?s=200&v=4
related: static-site-generator
released: April 14, 2020
short_description: A modern static site generator for Ruby.
topic: bridgetown
url: https://www.bridgetownrb.com/
---

A Webpack-aware, Ruby-powered static site generator for the modern Jamstack era, built by [Jared White](https://jaredwhite.com/). Built upon proven open source technology, like Jekyll, Bridgetown is a fast, scalable, modular, and thoroughly forward-looking framework for building websites and frontend applications.
```

---

- [Docs](https://github.com/github/explore/blob/master/CONTRIBUTING.md)
- [11ty Example](https://raw.githubusercontent.com/github/explore/master/topics/eleventy/index.md)
![CleanShot 2020-12-02 at 18 10 02](https://user-images.githubusercontent.com/18423853/100942713-d3b72c80-34c9-11eb-9b82-dfab6c0ff133.png)
- [related to](https://github.com/orgs/bt-rb/projects/1#card-50508324)

**Comment by jaredcwhite** [comment]
That sounds good to me!

**Comment by andrewmcodes** [comment]
Awesome!
