### ISSUE TITLE
docs: Install bridgetown

### ISSUE THREAD

**Issue by bkmgit** [bridgetownrb/bridgetown#211]
## Motivation

Many users may not have or may not want to use superuser privileges when setting up Bridgetown

## Suggestion

Consider adding documentation similar to [Jekyll](https://jekyllrb.com/docs/troubleshooting/#no-sudo) to use the command below before doing ```bridgetown new mysite```

```bash
# Ruby exports

export GEM_HOME=$HOME/gems
export PATH=$HOME/gems/bin:$PATH
```

**Comment by jaredcwhite** [comment]
We officially recommend installing Ruby & gems with rbenv, or another tool like it, and I don't think that requires superuser privileges. So I'll close this unless you think there's a permissions issue still with the rbenv approach.
