### ISSUE TITLE
docs: Evaluate problematic terminology within marketing materials

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#213]
I'm increasingly wary of some of the terms I included in the initial "pitch" for Bridgetown, namely:

* modern
* Jamstack

In popular usage among a lot of recent tools and companies (often with big VC bucks backing them), both terms have become truly overused and overwrought…and some of the connotations are arguably at odds with the general ethos of the Bridgetown project.

All I mean when I use the term "modern" is: willingness to evaluate new trends in the web dev industry as a whole and embrace that which is truly a power-up from past setups or methodologies. Example: Bridgetown swapping out the Ruby-based CoffeeScript and SCSS processing for a Webpack-based solution.

And by Jamstack, all I mean is: a static/prerendered site built and most likely deployed on a Jamstack-style host via a Git workflow: Netlify, Vercel, etc.

Unfortunately, in some circles the term "modern" is reserved for, well, a sprawling React frontend (for all intents and purposes). And Jamstack is increasingly becoming "ditch your tired ol' monolithic backend and use our serverless cloud functions and/or other likely-proprietary SaaS-style microservices".

I'm really torn. On the one hand, maybe we have the opportunity to "redefine" terms like modern or Jamstack to fit into a less "new hotness" bandwagon-y paradigm only benefiting a mere handful of JS frameworks and growth-hacking service providers. On the other hand…these terms increasingly feel like empty corporate speak no different than synergy and alignment and move the needle.

Maybe this little rant shouldn't even be a GitHub issue, but I think it's a problem we all face in the web dev community at one time or another (especially Rubyists), and so I'd love to come to some conclusions collectively as well.

**Comment by ParamagicDev** [comment]
While we're on the subject, perhaps "Webpack-aware" may scare some Jekyll users away. I've seen a trend of people sticking with Jekyll and other less "advanced" SSGs in favor of simplicity.

**Comment by jaredcwhite** [comment]
> While we're on the subject, perhaps "Webpack-aware" may scare some Jekyll users away. I've seen a trend of people sticking with Jekyll and other less "advanced" SSGs in favor of simplicity.

That's a good point… We should be mostly frontend bundling tool agnostic￼. Maybe Webpack's the default, but we provide the option for Snowpack or something else soon￼.

**Comment by ayushn21** [comment]
Sorry, off topic but this discussion reminded me of this tweet :D 
https://twitter.com/DennisCode/status/1331695899672596480?s=20

I completely understand where you're coming from with your thinking regarding the words "JAMStack" and "Modern"; but I think the root problem there is those terms are open to interpretation and in some cases and some people's minds, they've been hijacked with the meanings you've defined.

My opinion is that it's worth sticking with these terms but perhaps defining them better in some way. That's a very vague comment, I know. But a page like this: https://www.bridgetownrb.com/docs/jamstack quite comprehensively defines what Bridgetown means by "JAMStack".

Also something worth thinking about could be a "Bridgetown doctrine" similar to the Rails doctrine: https://rubyonrails.org/doctrine/.

That would set the stall out in no uncertain terms and make it very clear what Bridgetown is and what the project stands for.

Also on a sidenote, I found and tried Bridgetown because I was trying to hammer Webpack into Jekyll and got fed up and went looking for out of the box solutions. The specific phrase "Webpack-aware" caught my attention. So while I agree we should be front end bundling tool agnostic, changing this terminology could be a bit of a double edged sword. Whatever the way forward, I think we should be careful we're not alienating anyone based on their preconceptions.

**Comment by jaredcwhite** [comment]
@ayushn21 That GIF you linked to is sooo good 😂 

I appreciate all your points there, and now that I'm thinking about it, I bet we could condense several pages into one overarching "doctrine" page:

https://www.bridgetownrb.com/docs/philosophy
https://www.bridgetownrb.com/docs/jamstack
https://www.bridgetownrb.com/about/

That would make it easier to explain the goals of the project in general and also some of the nuances of the terminology and decision-making behind that.

**Comment by ayushn21** [comment]
Yeah I think that would be a good way to go! 👍

**Comment by manuelgomes** [comment]
Let me take a slightly different tack into it. As a lapsed technologist, when I saw the landscape of "Jamstack" I kind of went "oy vey!" - so I went shopping for a solution that seemed to orient along _healthy first principles_, that let me use a simple toolchain that I didn't need to learn in depth, that quickly let me build experience with its structure and workflow, and that didn't engage in... for lack of a better expression "wankery" or woo-woo, that it embraced the new in a way that made good conceptual sense.

Finding Bridgetown I just kind of went "Ah, yes, this is how you can easily knock re-usable blocks together and deliver a good experience to current expectations without having to become an expert in too much at once". 

One of Bridgetown's strengths is **strong conceptual integrity** that is clearly felt in the development experience. It suggests and coaxes me towards learning new technologies by showcasing them in an evidently useful and unobtrusive way, while allowing you to do a reasonable "quickie to get it out" that lends itself to interactive improvement as I learn.

If I may be forgiven the mixed metaphors, lays out for website building what The Zen of Python did for programming: here are some principles that will keep you out of trouble and serve as guard rails for your learning journey. It's a consisent experience, it has... truth, elegance and simplicity to it.

I wish I could put this in soundbite-friendly tidbits :)

**Comment by andrewmcodes** [comment]
@jaredcwhite @ParamagicDev There's lots of ways to use Bridgetown without Webpack. 

Maybe the word we are looking for is "webpack compatible"? 

What would be really awesome imo is if we extract all webpack related tags and logic into its own gem that could included or not via flag.

**Comment by andrewmcodes** [comment]
@cjilbert504 any thoughts?

**Comment by jaredcwhite** [comment]
Thanks @manuelgomes and @andrewmcodes for your insights. Lots of food for thought. I definitely want to continue to maintain Bridgetown's push for a soup-to-nuts happy path￼ install, but I certainly can see that working with a more modular design as well regarding different frontend tooling￼. It's inspiring to me that Rails for example gives you so much out of the box, but it's also possible to strip it down to the studs if you really need to. I also think we have a real opportunity to make waves in the Jamstack space without drinking every ounce of the Kool-Aid that comes with any shiny new tech￼ trend.

Last comment of 2020? Cheers everybody!

**Comment by jaredcwhite** [comment]
Closing in favor of new issue #220.
