### ISSUE TITLE
feat:  Search functionality

### ISSUE THREAD

**Issue by bkmgit** [bridgetownrb/bridgetown#216]
## Summary

It may be helpful to add search functionality to static sites.

## Motivation

This feature is available in other static site generators, for example:
https://gohugo.io/tools/search/

It would make finding content in generated sites and navigating them much easier.

## Guide-level explanation

When generating your static website, you would also generate a site index file that would enable a javascript program to quickly find content on your site.

Possible software that could be used includes:
https://fusejs.io/
https://lunrjs.com

Might also consider a separate gem to do the indexing.

## Reference-level explanation

- Further discussion needed before implementing this

## Drawbacks

- Maintenance overhead
- May complicate deployment
- 
## Unresolved Questions

A javascript browser solution is likely ok if adopted. In future, for larger sites one could consider integration with Elasticsearch or similar.

**Comment by ayushn21** [comment]
There's an official Bridgetown plugin that integrates Lunr.js.

https://github.com/bridgetownrb/bridgetown-quick-search

Would this accomplish the functionality you're after @bkmgit?

**Comment by bkmgit** [comment]
@ayushn21 Awesome. Thanks.
