### ISSUE TITLE
uninitialized constant Liquid::ParseTreeVisitor in project setup

### ISSUE THREAD

**Issue by pmackay** [bridgetownrb/bridgetown#221]
Running `bridgetown new` for a new project gave this error:
```
.gem/ruby/2.6.5/gems/liquid-render-tag-0.2.0/lib/liquid-render-tag/variable.rb:164:in `<class:Variable>': uninitialized constant Liquid::ParseTreeVisitor (NameError)
```

By separately installing the `liquid` gem it then worked fine. 

**Bridgetown Version**:
bridgetown 0.19.1 "Arbor Lodge"

**To Reproduce**
Try a new project install.

**Comment by jaredcwhite** [comment]
Thanks @pmackay, we'll double check this when implementing #223.

**Comment by jaredcwhite** [comment]
I would assume this could be due to the fact that outside of the bundle versions there was an older version of Liquid installed. Bridgetown now requires Liquid v5 and `liquid-render-tag` gem has been removed, so hopefully a moot point now.
