### ISSUE TITLE
Ruby 3 requires explicit Webrick dependency

### ISSUE THREAD

**Issue by julianrubisch** [bridgetownrb/bridgetown#222]
**Bridgetown Version**:
0.18.6

**To Reproduce**
install Ruby 3 and do `yarn start`

**Current Behavior**
```
[Bridgetown] bundler: failed to load command: bridgetown (/Users/jrubisch/.rbenv/versions/3.0.0/bin/bridgetown)
[Bridgetown] /Users/jrubisch/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require': cannot load such file -- webrick (LoadError)
```

Fixed by explicit adding of `gem 'webrick'` to the Gemfile. Is this something that should go into the gemspec?

- Ruby Version: 3

**Additional context**

**Comment by ayushn21** [comment]
Hey @julianrubisch, I believe this is fixed in v0.19.0 👍 

https://github.com/bridgetownrb/bridgetown/commit/2f9b409c35628e9493afbf76645804c2b3e52481
