### ISSUE TITLE
Clean command does not respect the config 

### ISSUE THREAD

**Issue by andrewmcodes** [bridgetownrb/bridgetown#232]
**Bridgetown Version**: `0.19.1`

**To Reproduce**

1. Create placeholder file

```sh
mkdir output && touch output/.placeholder
```

2. Edit `keep_files` in your config

```yml
# bridgetown.config.yml

# ...
keep_files: [".placeholder"]
# ...
```

3. Build the site

```sh
yarn build
```

>Note: this starts from the assumption `output` is your destination folder.

4. Verify `output/.placeholder` still exists
5. Run `yarn clean`//`bundle exec bridgetown clean`

**Current behavior**

`output/` will be nuked, along with the `.placeholder` file.

**Expected behavior**

Adding `.placeholder` to the `keep_files` array in the config will, as the docs say:

>When **clobbering** the site destination, **keep the selected files**. Useful for files that are not generated by bridgetown; e.g. files or assets that are generated by your build tool. The paths are relative to the destination.

**Computing environment (please complete the following information):**
 - OS: macOS Big Sur 11.0.1
 - Browser n/a
 - Browser Version n/a
 - Ruby Version `3.0.0`

**Additional context**

I'm thinking there is an underlying implication that this config option is to be used for builds, and adding to `keep_files` will just ensure that Bridgetown does not remove the files in the array when rebuilding. 

Would like to confirm or deny that theory before talking about whether the docs need to be a little more explicit or if this is actually a bug.

:heart:

**Comment by jaredcwhite** [comment]
Sounds like a bug at first place. I'll investigate.
