### ISSUE TITLE
docs: Redesign Website / Homepage

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#245]
Related issue: #220 

I'd like to significantly revamp the Bridgetown website & branding, especially the homepage. It was fine in a pinch when kicking off the project, but I'm ready to take it up a huge notch or two, especially as we approach the big 1.0 later this year.

I'll start posting a series of comments with prior art as inspiration for what we could do. I'm also open to the idea of bringing on an outside designer to provide a mockup and some extra pizzazz.

### Basic set of goals:

* Fancier logo
* Dark/light themes
* Rad typography
* More lively colors
* More social proof, examples, testimonials (now that the project has some!)
* Digestible features list with relevant docs links (Next.js homepage does this very well)
* Comparisons with competitive tools — why use Bridgetown and not (fill in the blank)?
* More of a tutorial-style intro to building a Bridgetown site, thus allowing feature-specific docs to become more technical and less "what the heck even is this" in nature

**Comment by jaredcwhite** [comment]
Jigsaw, a PHP site generator, has a nice homepage: https://jigsaw.tighten.co/

**Comment by jaredcwhite** [comment]
I've always been really impressed by Gridsome's website. https://gridsome.org/

**Comment by jaredcwhite** [comment]
I like the wacky shapes and colors on Render's site, and in particular the "rewriting copy" effect in the hero. https://render.com/

**Comment by ParamagicDev** [comment]
@leastbad showed me popper.

https://popper.js.org/

I really like it's design

**Comment by leastbad** [comment]
Just curious, what's your budget?

I'd like to get a $20,000-looking site for SR/CR, but I need to find someone talented enough to pull it off who is willing to work in the $2000 range. Turns out, that's no small feat.

**Comment by jaredcwhite** [comment]
> Just curious, what's your budget?

I haven't thought that far ahead, but sounds like I'd be in the same boat w/r/t price sensitivity…

**Comment by leastbad** [comment]
As Hampton said to Konnor, there's always sites like 99Designs... but you're really getting what you pay for.

The reason that the Popcorn site works as well as it does is that someone went through a full branding exercise, and then came up with a clever concept that worked with the name/theme of the library, and then had the skillset + invested the time to execute. You can't skip all of the middle steps and end up with something that raises the bar.

I attempted to go through Dribbble and pick out designers that had portfolio items which, if you squint just right, suggest that they could produce the sort of thing I'm hoping for. Unfortunately, Dribble monetizes by charging $300/month just to use their search engine without limitations.

The fact that Dribbble can and does charge $300 just for searching should be illustrative in terms of budget planning, and yet there's still so many devs who think paying anything for design work is highway robbery. Crazy double standard!

Unfortunately, this complete disconnect between value and price is why 99% of developer-driven web sites either look terrible ("I know Tailwind, I've got this!") or baldly cookie-cutter (I have a credit card and getting this theme I bought working was so hard, I'm just going to skip the customization stage).

**Comment by FezVrasta** [comment]
> The reason that the Popper site works as well as it does is that someone went through a full branding exercise, and then came up with a clever concept that worked with the name/theme of the library, and then had the skillset + invested the time to execute. You can't skip all of the middle steps and end up with something that raises the bar.

Thanks for the nice words about our website! It took more than 2 years to come up with a good idea 😂 (here's the related issue https://github.com/popperjs/popper-core/issues/377)

The rest of the website came naturally after we got the logo.

**Comment by leastbad** [comment]
Thanks for dropping by, @FezVrasta! It's honestly super amazing to see the evolution of the logo, even though it seems to skip about 500 steps in the very end. @atomiks knocked it out of the park!

I sent him a bunch of Twitter DMs but never heard back from him... it's safe to say that he has at least a few potential customers in this thread, if he's got any availability.

Anyhow, thanks again for Popper!

**Comment by jaredcwhite** [comment]
This new features page for Ghost is da bomb. https://ghost.org/features/

**Comment by jaredcwhite** [comment]
Oh the colors, the icons, the changelog. :heart: https://ghost.org/docs/

**Comment by jaredcwhite** [comment]
_Totally_ need to add this component to the new site!! https://github.com/ssleptsov/ninja-keys

**Comment by jaredcwhite** [comment]
Closing this, will open a new issue or two with specific things we want to add to the new website.
