### ISSUE TITLE
Unknown liquid filter fails silently

### ISSUE THREAD

**Issue by Dahie** [bridgetownrb/bridgetown#259]
So I'm playing around writing a small plugin around a liquid_filter. I'm now testing the gem in my project and found that the new liquid_filter is not found and that calling the unknown liquid_filter does not throw any errors.

**Bridgetown Version**:

bridgetown 0.20.0 "Healy Heights"

**To Reproduce**

1) create a new site
2) add `{{ "string" | unknown_liquid_filter}}` to index.md
3) run `bridgetown serve`
4) visiting the site shows it prints "string" without logging an error for the unknown liquid filter

**Current behavior**

Applying an unknown liquid_filter does nothing, neither logging a warning, error or anything.

**Expected behavior**

I'd have expected it either throws an error and holds the liquid generator. Alternative it should at least provide a warning in the log.

**Computing environment (please complete the following information):**
 - OS: OSX 11.2.3
 - Browser Firefox
 - Browser Version 86.0.1
 - Ruby Version ruby 3.0.0p0

**Comment by jaredcwhite** [comment]
That's the default behavior, unknown filters are ignored. You can change that by setting the config key:

```yaml
liquid:
  strict_filters: true
```

**Comment by Dahie** [comment]
Ah, I missed that! Thank you!
