### ISSUE TITLE
docs: /docs/installation/windows

### ISSUE THREAD

**Issue by b-hayes** [bridgetownrb/bridgetown#282]
**UPDATE:** putting the call out for a PR! See: https://github.com/bridgetownrb/bridgetown/issues/282#issuecomment-854798183

----

## Motivation

The recommendation to follow these steps:
https://gorails.com/setup/windows/10
caused me headaches for several hours.

## Suggestion

This is what I had to do to get things working.

I had to install gcc and make **before** doing the set of dependencies to install and rbenv install on the recommended page:
https://gorails.com/setup/windows/10

```
sudo apt install gcc
sudo apt install make
```

I also broke things when copying the echo into .bashrc commands because there was no newline at the end of my file (from last time I copied commands like this) and it broke everything and took me a while to set things right.
I suggest (if you guys have access to https://gorails.com/setup/windows/10 ) is to add a new line first and maybe a comment.
```
echo "\n#Ruby setup" >> ~/.bashrc
```

**Comment by jaredcwhite** [comment]
Thanks @b-hayes for the feedback. I have access to the GoRails Slack so I'll pass your feedback along.

**Comment by ParamagicDev** [comment]
Let me clarify some points here just for future readers:

A.) always install `build-essential`

`sudo apt install build-essential`

This will come with the following:

- dpkg-dev (>= 1.17.11)
Debian package development tools

- g++ (>= 4:5.2)
GNU C++ compiler

- gcc (>= 4:5.2)
GNU C compiler

- libc6-dev
GNU C Library: Development Libraries and Header Files

https://packages.ubuntu.com/xenial/build-essential

all of which are generally recommended for Ruby installations especially when building from source.

Rbenv will build from Ruby versions from source using Ruby-install.

https://github.com/rbenv/rbenv#installing-ruby-versions

Here is the Ruby-build project wiki which shows what's recommended to build Ruby installations:

https://github.com/rbenv/ruby-build/wiki#suggested-build-environment

- Ubuntu

```bash
apt-get install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev
```

sorry I wasn't here to help you debug this earlier!

hopefully this can help someone else in the future!

**Comment by jaredcwhite** [comment]
I'd like to self-host our own Windows documentation so we don't need to link to GoRails (though of course that's a wonderful resource) — however, I'm unable to test/verify Windows docs because I don't have a Windows machine.

I'll gladly merge a PR from anyone who can successfully test/write-up an end-to-end setup process!

**Comment by b-hayes** [comment]
I had been keeping your last message in my inbox all this time thinking I'd come back and do PR for you but probably isn't going to happen any time soon. Could probably just mention installing build-essentials as @ParamagicDev described before directing them to the usual setup instructions from GoRails. That might cover it.
However, ill probably be forced to make time to test the setup later 😂 when I get my new machine sent to me.

**Comment by jaredcwhite** [comment]
Again, any PR on this is gladly accepted…meanwhile, closing this issue.
