### ISSUE TITLE
0.21 beta resources: permalink starting with dot or including multiple dots don't output correct url

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#290]
If you have a permalink in your front matter like `/.nojekyll` or `gosh.so.many.dots`, it's either dropping all the middle segments or swallowing the dotfile resulting in "/".

**Comment by ParamagicDev** [comment]
silly question, does this happen if you surround the permalink in quotes?

```md
---
permalink: "/.nojekyll"
```

**Comment by jaredcwhite** [comment]
Good question, but no I verified there isn't an issue with the old content engine. I do some futzing around with file extensions in the new permalink code and there must be a logic bug lurking in there. I started to look into it but haven't found the smoking gun yet.

**Comment by jamie** [comment]
This report originally came from me, using the same trick I do on my blog (which is not using the new content engine).

Initial buggy behaviour was https://github.com/jamie/food.tracefunc.com/commit/979d4731f0db691a036a7bf72bd63edadfef877e which did quote it.

**Comment by jaredcwhite** [comment]
Think I forgot to close this after the beta release.
