### ISSUE TITLE
Investigate possible areas of refactoring via dry-rb

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#307]
I've been eyeing the [dry-rb](https://dry-rb.org) ecosystem for a while now, and I think there are some areas in Bridgetown where we could strip out a fair bit of code and leverage what they've built, for example [dry-events](https://dry-rb.org/gems/dry-events/0.2/) to power hooks.

**Comment by jaredcwhite** [comment]
Kinda feel like we shouldn't add any more gem dependencies at this point unless it's super urgent, so will close this for now.

**Comment by akarzim** [comment]
Why not drop the very greedy Rails-related gems (activemodel, activesupport) for lightweight, robust, powerful and framework-agnostic dry-rb gems? Furthermore, these gems are stable, well-designed and used extensively by Hanami, the next-generation web framework! Maybe for the 2.0 roadmap? ;)

To support my point: https://solnic.codes/2022/02/02/rails-and-its-ruby-dialect/

**Comment by jaredcwhite** [comment]
@akarzim I appreciate the suggestion. My "dialect" remains fairly close to the Rails way on a lot of stuff, and any steps we take to move away from relying as much on them we'd probably just bring a subset of the desired functionality in-house. The dry-db ecosystem doesn't appeal to me by and large, but I'm glad there are folks out there who find value in it.
