### ISSUE TITLE
docs: Minitest "bundled configuration" and documentation page aren't wired up

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#309]
Looks like https://www.bridgetownrb.com/docs/testing and the [Minitest bundled config](https://www.bridgetownrb.com/docs/bundled-configurations#automated-test-suite-using-minitest) aren't cross-linked (and the testing page uses the old external apply automation).

**Comment by jaredcwhite** [comment]
Can you take a look at this @ayushn21? TIA

**Comment by ayushn21** [comment]
On it!

**Comment by ayushn21** [comment]
I think we should add @ParamagicDev's Cypress automation as a bundled configuration and simplify the Cypress section on the testing page; in addition to linking the Minitest section to the bundle configurations page.

I'll get to it later today :)

**Comment by jaredcwhite** [comment]
Sounds great!
