### ISSUE TITLE
docs: Simplify docs for cypress testing

### ISSUE THREAD

**Issue by ayushn21** [bridgetownrb/bridgetown#311]
Our Cypress testing docs can be simplified by adding Cypress to our bundled configurations. We could then remove the sections describing manual setup.

Related to https://github.com/bridgetownrb/bridgetown/issues/309#issuecomment-844974463

**Comment by robertguss** [comment]
Hi @ayushn21. My name is Robert and I work on the DX team at Cypress. Is there anything I can do to help with this?

**Comment by ayushn21** [comment]
Hey @robertguss, thanks so much for dropping in. We wanted to automate setting up Cypress within Bridgetown using our [Bundled Configurations](https://www.bridgetownrb.com/docs/bundled-configurations) feature; rather than describe the setup process on our website as it is currently.

The work's nearly done; we just need to ensure we're terminating all spawned processes (Bridgetown server, Webpack dev server, Cypress) after the test run is complete.

We're in the process of migrating all our scripts from Yarn to Rake, so just waiting till that's done so we don't have to do the work twice. 

I don't think there's anything we need from you at the moment; but if you have any suggestions please do share :)

Thanks again!

**Comment by ParamagicDev** [comment]
hey this means I could probably deprecate my automation for Cypress!

**Comment by ayushn21** [comment]
Yup you can! I pretty much copy pasted that into Bridgetown core!
