### ISSUE TITLE
The bt-postcss config disables Tailwind config from working

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#315]
**Bridgetown Version**:
0.21.0.beta3

**To Reproduce**:
If you run the `tailwindcss` bundled configuration, and then run `bt-postcss`, it seems like it breaks Tailwind from importing in the main CSS file.

**Expected behavior**:
Either we want it not to interfere with Tailwind working, or it should detect the existing presents of Tailwind and not continue with the repo changes.

**Comment by ayushn21** [comment]
I can't ever see these two configurations being used in conjunction to be honest. Though I agree that this is a problem. 

I propose that we add a warning when both these configurations are run saying "This will overwrite your `postcss.config.js`, do you want to continue?".

In the future we could probably look at doing something a bit more clever, but it's non-trivial as the order of the postcss plugins is very important and our users could have any number of plugins in their config file prior to running this configuration.

**Comment by jaredcwhite** [comment]
Yeah, I know it's non-trival to sort this out…all I know is I tried setting up a new project using both and then was scratching my head wondering why the `@tailwind` directives in the index CSS were just getting output to the bundle as-is and Tailwind was broken. So maybe a warning would be helpful at the least.
