### ISSUE TITLE
docs: installation/ubuntu/ "Unable to locate package libgdbm5"

### ISSUE THREAD

**Issue by harry-wood** [bridgetownrb/bridgetown#321]
The install instructions at https://www.bridgetownrb.com/docs/installation/ubuntu/ list the package libgdbm5, but on a newer ubuntu versions it needs to be libgdbm6. Otherwise *"Unable to locate package libgdbm5"*.  I think it applies to ubuntu focal (20.04LTS) onwards.

**Comment by jaredcwhite** [comment]
Thanks @harry-wood. Some additional context: https://github.com/rbenv/ruby-build/issues/1211

We'll update the docs. :+1:

**Comment by jaredcwhite** [comment]
The docs have been updated and I've tested out a full setup on a fresh Ubuntu v20 install. Thanks for pointing this out. (Also including Node v16 instructions.)
