### ISSUE TITLE
Purgecss doesn't keep tailwind media query class definitions

### ISSUE THREAD

**Issue by arusa** [bridgetownrb/bridgetown#333]
**Bridgetown Version**:

bridgetown 0.21.0 "Broughton Beach"

**To Reproduce**

```
bridgetown new site --use-postcss
cd site
bridgetown configure tailwindcss
```

Then use styles like `sm:p-4` or `sm:text-2xl` and then run:

```
yarn build
# or:
bundle exec bridgetown build
```

**Current behavior**

The css gets purged:

```
...
           PurgeCSS Purging main.66664f4db978266a02be.css
           PurgeCSS Done. No apparent change in file size (14kB).
...
```

But the used styles containing a ':' are missing in the purged css file.

```
$ grep -r 'sm:p-0' output/index.html
output/index.html:  <div class="flex flex-col p-4 sm:p-0 sm:flex-row space-x-8 items-center">
# grep the purged css file:
$ grep -r 'sm\\:p-0' output/_bridgetown/static/css/main.66664f4db978266a02be.css
# grep also the css files that `yarn start` produces (not purged)
$ grep -r 'sm\\:p-0' output/_bridgetown/static/css/*.css
output/_bridgetown/static/css/main.2c9059b036bc50cb348f.css:  .sm\:p-0 {
output/_bridgetown/static/css/main.2c9059b036bc50cb348f.css:  .sm\:p-0\.5 {
output/_bridgetown/static/css/main.8af74ae344fa3408d238.css:  .sm\:p-0 {
...
```

**Expected behavior**

PurgeCSS should find styles like `sm:p-4` in `./output/**/*.html` and therefore keep those class definitions in the css file.

**Computing environment (please complete the following information):**

 - OS: MacOS 11.4
 - Ruby Version: 2.7.3p183

**Additional context**

I found some issues and tried adding a different regex with defaultExtractor (`/[A-Za-z0-9-_:\/]+/g`, `/[^<>"'`\s]*[^<>"'`\s:]/g`,...), but until now nothing helped.

https://github.com/FullHuman/purgecss/issues/86
https://github.com/tailwindlabs/tailwindcss.com/pull/18

**Comment by arusa** [comment]
I think I have solved the problem.

It seems populating the purge array in the `tailwind.config.js` solved the problem:

```js
module.exports = {
  purge: [
    'frontend/javascript/*.js',
    './output/**/*.html'
  ],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {},
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
```

As described above I also added `defaultExtractor` to purgecss.config.js:

```js
module.exports = {
  content: ['frontend/javascript/*.js', './output/**/*.html'],
  output: './output/_bridgetown/static/css',
  defaultExtractor: content => content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || []
}
```

**Comment by arusa** [comment]
That worked on my Mac, but it didn't work when deploying to production using dokku.

I could replicate the problem locally when setting `NODE_ENV=production` while running:

`NODE_ENV=production yarn deploy`

Only this triggered tailwind to purge the css files. But in this case tailwind reduced the css size to 12kb and PurgeCSS again reduced it to 9kb.

After changing the purge array in the tailwind.config.js back to `purge: []` it seems to work.

So the missing part was the defaultExtractor in the `purgecss.config.js`, but maybe I had to do a `bridgetown clean` to make it work.

```
module.exports = {
  content: ['frontend/javascript/*.js', './output/**/*.html'],
  output: './output/_bridgetown/static/css',
  defaultExtractor: content => content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || []
}
```

**Comment by jaredcwhite** [comment]
Thanks @arusa. I'm fuzzy on how Tailwind and Purge CSS configs interact with each other, but glad you got it sorted out. :+1:

**Comment by work-leonid** [comment]
Hi, I have the same problem with tailwind and purgecss. I have not been able to solve it using the suggested options. 
It seems that the problem is in [postcss focus within ](https://github.com/csstools/postcss-focus-within) 

Bridgetown uses version 3.0.0 of this plugin. In April there was [an update](https://github.com/csstools/postcss-focus-within/releases/tag/4.0.0) of this package to 4.0.0. With a fix for "Fixed: Allow :focus-within to appear escaped in a selector". 

But I don't understand how I can update my local copy of this package. yarn upgrade doesn't update this package, removing doesn't work either.

**Comment by stephaneliu** [comment]
Thanks @arusa for the fix. I'm in the same boat as @jaredcwhite in regards to config interaction. I didn't think your fix would work since TailwindCSS declares a `defaultExtractor`. But..it works.

I did modify package.json to pass NODE_ENV for to activate purge on deployments:

```
  "scripts": {
    ...
    "webpack-build": "webpack --mode production --node-env=production",
    ...
  },

```

**Comment by danielehrhardt** [comment]
Is there a more general Solution for this Problem?
