### ISSUE TITLE
docs: Replace "Jamstack" terminology with something better

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#335]
Related: #220, #213

The term Jamstack seems to be increasingly problematic with Netlify essentially controlling the narrative based on their particular flavor of web hosting. Vercel doesn't use the term. Render (my preferred hosting platform) doesn't use the term. I also see it increasingly used to refer to architectures solely based on JavaScript. Not what we're aiming at, nor do I think such deployments are easily maintainable over the long term.

I still think we can casually employ the Jamstack term somewhere for SEO/educational purposes, but I'd like to greatly deemphasize it in favor of more concrete terms like static generation, atomic deploys, CDNs, and dynamic hybrids: aka a single monorepo/Ruby stack featuring a Bridgetown static site + backend monolith (Roda/Sinatra/Rails/whatever) which is a very cool pattern.

**Comment by debashis-biswal** [comment]
@jaredcwhite I am looking into this.

**Comment by jaredcwhite** [comment]
**Progressive site generator / generation.**

I think that terminology captures what we're going for here. It's no longer just about static generation. It's about a wide continuum from static routes, to dynamic routes￼ using cached build-time data, to dynamic routes using live data, to async workers running out-of-band with request/response cycles. Use the right tool for the right job￼ — just like "progressive enhancement" on the frontend.￼ Progressive generation is that, for the backend.￼

**Comment by jaredcwhite** [comment]
Also:

**HTML-first development** (along with HTML-Over-the-Wire techniques).

**Ruby-first development**.

Not JS, not GraphQL, not the "API economy" (which I have a big problem with as an advocate for self-hosted open source solutions to problems). Ruby & HTML are the building blocks here, with all the advantages those paradigms afford.
