### ISSUE TITLE
Resource content engine only loads one file in subfolders under _data

### ISSUE THREAD

**Issue by ayushn21** [bridgetownrb/bridgetown#338]
**Bridgetown Version**: 0.21

**To Reproduce**

* Create a new project: `bridgetown new data_test`
* Add `content_engine: resource` to `bridgetown.config.yml`
* Create a directory under `_data` called "gallery"
* Create two files under that directory called `album_1.yml` and `album_2.yml` and put some content in them
* Run `bundle exec bridgetown console` and then `site.data.gallery`

**Current behavior**

Only the data from one of the album files will be printed.

```
>> site.data.gallery
{
  "album_2" => [
    [0] {
      "file" => "2.jpg"
    },
    [1] {
      "file" => "2.jpg"
    }
  ]
}
```

**Expected behavior**

The data from both files should be printed.

**Computing environment:**
 - OS: macOS 11.3.1
 - Ruby Version: 2.7.2p137

**Comment by jaredcwhite** [comment]
Huh, that's definitely unexpected. 😕 I'm guessing there must be an inadvertent overwriting of a preinitialized hash lurking somewhere in there.

**Comment by ayushn21** [comment]
Yeah it's pretty strange ... I took a quick peek at the code but couldn't see any obvious issue

**Comment by jaredcwhite** [comment]
> Huh, that's definitely unexpected. 😕 I'm guessing there must be an inadvertent overwriting of a preinitialized hash lurking somewhere in there.

Narrator: there was.
