### ISSUE TITLE
feat: Preserve order of related records in relations

### ISSUE THREAD

**Issue by stevegeek** [bridgetownrb/bridgetown#360]
## Summary

a suggestion in relation to resource relations: it would be nice if the order the related resource slugs are specified was maintained in the relation collection . This could be easy simply by flipping the order of operations in `belongs_to_relation_for_type` say to `map` `resource.data[type]` to resources rather that iterating over the resource collection and selecting only the related ones

## Motivation

The data related is often displayed by iterating the relation collection and then the order matters.

## Reference-level explanation

Eg, obv not the most efficient implementation due to repeated find calls, but just to show what i mean  

```
def belongs_to_relation_for_type(type)
        if resource.data[type].is_a?(Array)
          mapped = resource.data[type].map do |slug|
            other_collection_for_type(type).resources.find { |other_resource| other_resource.data.slug == slug }
          end
          mapped.compact
        else
```

**Comment by jaredcwhite** [comment]
Great suggestion @stevegeek!

**Comment by stevegeek** [comment]
Great thanks!
