### ISSUE TITLE
`link` Liquid tag and Resources

### ISSUE THREAD

**Issue by stevegeek** [bridgetownrb/bridgetown#363]
Think there maybe something up with `link` tags and resources... in `Bridgetown::Tags::Link` the conditonal in render `if item.relative_path == relative_path` , with `Resource` objects is comparing a `Pathname` with a string, hence is always false even if the same.

if I add a `.to_s` to the `Pathname` the match works but then the link output is the HTML of the target page rather than its path

**Bridgetown Version**:
0.21.3

**To Reproduce**

`{% link _collection/filename.md %}` with resource engine

**Current behavior**

error about no matching page

**Expected behavior**

A link!

**Comment by jaredcwhite** [comment]
@stevegeek There was indeed an issue here! Also found one in the `url_for` helper. Fixed in #389
