### ISSUE TITLE
console bug with amazing_pring

### ISSUE THREAD

**Issue by captproton** [bridgetownrb/bridgetown#397]
Hi, I fired up bridgetown console and got this:
> % bridgetown console
> /Users/carltanner/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/bridgetown-core-0.21.4/lib/bridgetown-core/commands/console.rb:32:in `require': cannot load such file -- amazing_print (LoadError)

**Bridgetown Version**:
"bridgetown 0.21.3 "Broughton Beach"

**To Reproduce**
bridgetown console
/Users/carltanner/.asdf/installs/ruby/3.0.1/lib/ruby/gems/3.0.0/gems/bridgetown-core-0.21.4/lib/bridgetown-core/commands/console.rb:32:in `require': cannot load such file -- amazing_print (LoadError)

**Current behavior**
If the user doesn't have amazing_print installed already installed she gets the error above.

**Expected behavior**
Something along these lines:
> ~ % bridgetown console
>          Starting: Bridgetown v0.21.4 (codename "Broughton Beach") console…
>       Environment: development
> Configuration file: none
>   Reading files...
>                    done!
> Running generators...
>        Pagination: disabled. Enable in site config with pagination:\n enabled: true
                    done!
>           Console: Now loaded as site variable.
>irb(main):001:0>

**Computing environment (please complete the following information):**
 - OS: MacOS 11.6
 - Browser iTerm2
 - Ruby Version ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-darwin20]

**Additional context**
my guess is that anyone that has used this successfully already has awesome_print in her base gemset

**Comment by jaredcwhite** [comment]
In order to load the correct gem environment, all commands need to be run prefixed by `bundle exec`, aka `bundle exec bridgetown console`. If that still shows a error, feel free to reopen this issue.
