### ISSUE TITLE
Relocate `Publisher` class functionality to `Resource::Base` concern

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#403]
It seems like a stretch to have this as its own class…really could just be refactored down to one or two methods on `site`.

**Comment by armahillo** [comment]
`Publisher`:
https://github.com/bridgetownrb/bridgetown/blob/main/bridgetown-core/lib/bridgetown-core/publisher.rb

`Site`
https://github.com/bridgetownrb/bridgetown/blob/main/bridgetown-core/lib/bridgetown-core/site.rb

**Comment by jaredcwhite** [comment]
Actually…I believe this is only relevant to resources now, so it can just hang off of `Resource::Base`!

**Comment by jaredcwhite** [comment]
Seems like this wasn't fully completed after all, plus there's a missing gap of logic causing the bug of #557. Concerning this wasn't caught by the test suite. Will investigate!
