### ISSUE TITLE
feat: Add `bin/bt` alias

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#411]
From a comment by @ayushn21:

> Do you think it's worth duplicating bin/bridgetown to bin/bt? It's a tiny amount of code that's unlikely to change so duplicating the file isn't the big deal in my opinion. It'll avoid putting the onus on the developer to set up an alias and provide a concise way to invoke commands out of the box.

**Comment by jaredcwhite** [comment]
> Hey @jaredcwhite! Can I take this one?

@meg-gutshall Go for it!

**Comment by meg-gutshall** [comment]
Would you like me to update the documentation along with this? I'm not exactly sure how to word that there's now an alias for the `bridgetown` command. Any ideas?

**Comment by jaredcwhite** [comment]
Thanks @meg-gutshall for digging into this. So…it's one of those non-obvious things to be sure, but that's not actually the right `bin/bridgetown` to alias (the one inside the core gem there is what gets installed globally by RubyGems).

What the issue is referring to is the "binstub" which gets generated by Bundler in the new site template. This is brand new in the v1.0 alpha—when a new site is created it will have a `bin/bridgetown` inside of it which is really just a handier way of running `bundle exec bridgetown`.

If we can update the `new` command so that after Bundler generates binstubs we copy `bridgetown` to `bt`, that would be ideal.

Let me know if that makes sense (or not￼ 😅)!

**Comment by meg-gutshall** [comment]
Hi @ayushn21, thank you for the detailed description! I plan to tackle this tonight when pairing with a friend of mine.

**Comment by jaredcwhite** [comment]
Fixed in https://github.com/bridgetownrb/bridgetown/commit/f1a65723a28b531fadffc99be122d913d5077053
