### ISSUE TITLE
Investigate improving live reloading in development

### ISSUE THREAD

**Issue by ayushn21** [bridgetownrb/bridgetown#416]
Currently, live reloading works by polling an endpoint that checks for changes and refreshes the page:

https://github.com/bridgetownrb/bridgetown/blob/90a73bb5c74f005dddd90e263424d9872fde450d/bridgetown-core/lib/bridgetown-core/utils.rb#L402
https://github.com/bridgetownrb/bridgetown/blob/90a73bb5c74f005dddd90e263424d9872fde450d/bridgetown-core/lib/bridgetown-core/rack/routes.rb#L56

This works well but I think there's scope for improvement here. 

The first approach worth investigating is [Server Sent Events](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events). We should be able to set up the `live_reload` endpoint to stream responses using the [Roda Streaming Plugin](http://roda.jeremyevans.net/rdoc/classes/Roda/RodaPlugins/Streaming.html). On the client side we can use [`EventSource`](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) to create the connection, listen for the events and trigger a refresh. There's still a lot of unknowns like how to watch the files and send responses; or whether this approach will even work.

If the above doesn't work, it's also worth investigating a WebSockets based approach I reckon.

**Comment by jaredcwhite** [comment]
Another option I found is the message_bus plugin: https://github.com/jeremyevans/roda-message_bus
example app: https://github.com/jeremyevans/lila_shell

It uses the MessageBus gem from the Discourse folks: https://github.com/discourse/message_bus
