### ISSUE TITLE
feat: Changes API based on Git

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#43]
We have Git. We can read a site repository and understand the content in context.

Imagine a `bridgetown changes` command that provides a user-friendly, well-formatted list of additions, changes, and deletions in the content of the website. It would respect front matter, markdown, page permalinks, data files, etc. Also imagine this as an API which could be consumed easily by editor software. Also imagine this as something which could be attached to some sort of high-level editorial documentation, like a PR for non-nerds.

Imagine…

**Comment by jaredcwhite** [comment]
Wondering if this should be in core or should be a separate plugin, but either way I'd still love to see this!

**Comment by jaredcwhite** [comment]
Starting this as a standalone plugin (woohoo!), but I'll keep the issue open here to track progress as we'll probably want to mention it in official docs.

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue.

It's a good idea, but I think Bridgetown should focus on a stable core and leave things like this for plugins.

Also, I'd say there are already a ton of tools making human-readable (and non-tech friendly) changelogs from Git data, and Github PRs.

By closing some old issues we reduce the list of open issues to a more manageable set.
