### ISSUE TITLE
Add an `--environment` flag to `bridgetown start`

### ISSUE THREAD

**Issue by ayushn21** [bridgetownrb/bridgetown#437]
Currently, as far as I can tell, the only way to set the Bridgetown environment is via the `BRIDGETOWN_ENV` environment variable. 

I reckon it'll be useful to allow users to set this while starting the server as well.  We could have something like:

```shell
bin/bridgetown start --environment test
```

and

```shell
bin/bridgetown -e test
```

**Comment by jaredcwhite** [comment]
Resolved in https://github.com/bridgetownrb/bridgetown/commit/c6e6d454e5f89d3889660b21b4c9e0f46af3f68f
