### ISSUE TITLE
tweaks to Render config script

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#459]
Couple of small items which have come up:

* Need to specially have `BRIDGETOWN_ENV` = `production`
* Need to add a `.ruby-version` file to the repo if there isn't one already, with the latest 2.7 or 3.0 version, otherwise Render chokes because it defaults to Ruby 2.6.

**Comment by ayushn21** [comment]
> Need to add a .ruby-version file to the repo if there isn't one already, with the latest 2.7 or 3.0 version, otherwise Render chokes because it defaults to Ruby 2.6.

I don't think this should be within the scope of a Render config. It feels like a more general configuration option. Perhaps we should put a default `.ruby-version` file in our site template?
