### ISSUE TITLE
Add `.ruby-version` to new site repo

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#468]
When a new project is created, add the current Ruby version to a new `.ruby-version` file.

**Comment by manuelgomes** [comment]
Perhaps including detection of ruby management via [asdf](https://asdf-vm.com/) as to generate a .tool-versions instead?

While [asdf _can_ read .ruby-version](https://asdf-vm.com/guide/getting-started.html#using-existing-tool-version-files) given the `legacy_version_file = yes` configuration, this would make the process entirely seamless for the user.

**Comment by jaredcwhite** [comment]
Thanks for mentioning that @manuelgomes. One of the reasons though it's actually important to include `.ruby-version` is to ensure hosting services and other users—whether using RVM, rbenv, asdf, or something else—will switch to the correct Ruby version. `.tool-versions` would only benefit the asdf user. Maybe we can just document the `legacy_version_file = yes` tip in our installation instructions/default readme template.

**Comment by jaredcwhite** [comment]
Resolved in commit https://github.com/bridgetownrb/bridgetown/commit/0f66a7ebf706f278a40b0cf7add934ea251466f5
