### ISSUE TITLE
docs: Improve internal API documentation and update comment format to Yard

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#47]
UPDATE: see #283 

----

Looking through the generated docs from Yard:
https://rubydoc.info/gems/bridgetown-core/

Right now any useful information contained therein is very spotty and some files have no documentation whatsoever. We should prioritize incremental progress towards a fairly complete set of documentation around the core set of Bridgetown objects. Not as worried about ancillary objects like a string utility here or a tag there.

**Comment by jaredcwhite** [comment]
Definitely want to make sure we're providing comprehensive hover info for editors using https://solargraph.org

**Comment by jaredcwhite** [comment]
Also I'm assigning to you @ParamagicDev but obviously I can help out as well 😃

**Comment by ParamagicDev** [comment]
@jaredcwhite what branch would you like me to fork off of? Main?

**Comment by jaredcwhite** [comment]
@ParamagicDev yep, that's fine

**Comment by jaredcwhite** [comment]
Some improvements in #171, including switching YARD's text processing to Markdown format

**Comment by jaredcwhite** [comment]
Continuing to make progress in 0.20…still more to do though! 🤪
