### ISSUE TITLE
Issue with Faraday and httpclient

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#480]
I'm not sure exactly what's going on, but somehow in Faraday's move to 2.0, they broke the 1.9 line as well.

A workaround is to run this:

```sh
bundle add httpclient
```

**Comment by ParamagicDev** [comment]
@jaredcwhite i believe they removed the Net::HTTP as the default adapter and you have to manually set an HTTP adapter

**Comment by mperham** [comment]
2.0.1 now defaults to net/http.

**Comment by iMacTia** [comment]
I released 1.9.0 with adapter dependencies being too relaxed and forgot that v2 of each adapter has hard dependencies on the client libraries (e.g. httpclient, patron, etc...)

Faraday 1.9.1 is now out and fixes that

**Comment by jaredcwhite** [comment]
Fix confirmed, closing.
