### ISSUE TITLE
The `render` stage of site building may cause Git `fatal` errors for every rendered page

### ISSUE THREAD

**Issue by johlym** [bridgetownrb/bridgetown#490]
**Bridgetown Version**:
bridgetown 1.0.0.beta2 "Pearl"

**To Reproduce**
- Have an existing Bridgetown site in a GitHub repository
- Pull the source tarball down from the repository for deployable branch (ex: `wget -O -  https://github.com/username/repo-name/tarball/master | tar xz`
- `cd` into the resulting directory
- ensure the correct Ruby and Node.js versions are active within the environment
- run `bundle install` and `yarn install` to ensure all libraries are installed within the environment
- run `bridgetown start` or `bridgetown deploy` (any command that generates stuff for `/output`)

**Current behavior**
Bridgetown builds the site as instructed

**Expected behavior**
Bridgetown builds the site as instructed
One copy of `fatal: not a git repository (or any of the parent directories): .git` is printed for every generated page in `output`
(For Heroku, a second line is printed: `Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).`)

**Screenshots**
![CleanShot 2022-02-03 at 16 11 38@2x](https://user-images.githubusercontent.com/5686227/152450426-f2f61c2e-89e5-4d5b-b446-3bda1ff6471f.jpg)

![CleanShot 2022-02-03 at 16 11 45@2x](https://user-images.githubusercontent.com/5686227/152450433-fe069693-778a-48a0-837d-95a8bd08b340.jpg)

**Computing environment (please complete the following information):**
 - OS: verified macOS 12.2 and Linux (Heroku)
 - Browser: n/a
 - Browser Version: n/a
 - Ruby Version (check with ruby -v): Reproduced with Ruby 3.0.3

**Additional context**
I do not see a reason why the render stage should need to do _anything_ git-related. A proper `.gitignore` would omit any produced output, and if the site is being deployed elsewhere and not pulled down from source control using `git clone`, this will always be an issue–the render stage assumes it's always being run in within an active Git repo.

I confirmed this is happening in the `render` stage by way of adding `puts` statements [in `processable.rb`](https://github.com/bridgetownrb/bridgetown/blob/main/bridgetown-core/lib/bridgetown-core/concerns/site/processable.rb#L18). I lost the scent after that without shoving more `puts` in a bunch of places.

**Comment by jaredcwhite** [comment]
I'm not able to reproduce this (for example I downloaded `https://github.com/bridgetownrb/fundraising-site/tarball/main`, extracted it, ran bundle/yarn install, and ran `bin/bridgetown deploy` without issue). If you can produce a link to your repo with this issue, I'll investigate further.

**Comment by johlym** [comment]
Wild. Here's where I'm seeing it: https://johlym/johnathan-org. I'll keep poking at it–yank stuff out until it goes away.

**Comment by johlym** [comment]
I've narrowed this down to the `bridgetown-sitemap` [plugin](https://github.com/ayushn21/bridgetown-sitemap). I'll open an issue there.
