### ISSUE TITLE
New site command with postcss from docs doesnt work as expected

### ISSUE THREAD

**Issue by stevegeek** [bridgetownrb/bridgetown#495]
In https://www.bridgetownrb.com/docs/bundled-configurations it is suggested to use tailwind to start new project with the option `--use-postcss`

However the project is created with the option in the filename:

`stephen$ bridgetown new my_project --use-postcss`

```
yarn install v1.22.4
error package.json: Name contains illegal characters
```

```
stephen$ ls -al
drwxr-xr-x  20 stephen  staff   640 Feb 12 18:20 my_project --use-postcss
```

**Bridgetown Version**:
1.0.0-beta2

**To Reproduce**

do

`bridgetown new my_project --use-postcss`

**Computing environment (please complete the following information):**
MacOS

ruby 3.0.2

**Comment by jaredcwhite** [comment]
@stevegeek Yeah that flag was removed in 1.0.0 because PostCSS is now the default — I believe the documentation is updated on the [edge site](https://edge.bridgetownrb.com/docs/bundled-configurations).
