### ISSUE TITLE
docs: Ideas for Improving the Windows Documentation

### ISSUE THREAD

**Issue by subsevenx** [bridgetownrb/bridgetown#501]
## Motivation

The documentation for setting up a local dev environment on Ubuntu is pretty robust and thorough. The same instructions could also be applied to an Ubuntu subsystem on Windows. 

At the moment, the Windows Bridgetown docs link out to a [Go Rails](https://gorails.com/setup/windows/10) tutorial that, while informative and correct, might confuse some readers (as it's a tutorial on installing Rails; thought I know it is mentioned in the docs to come back before getting to that part) and includes most of what we already have on the Ubuntu docs.

## Suggestion

I noticed the Windows documentation has a partial `{%@ "docs/install/node_on_linux" %}`, which includes the instructions from the Linux guide on how to install node. 

Perhaps we could create a partial for the Ubuntu guide in full and include it in the Windows documentation. The only things that would be missing are the instructions for the installation of WSL itself and the issue about auto-regeneration outside of the Linux file filesystem on Windows. The WSL instructions could either be included at the very beginning of the documentation or we could [link to the official documentation](https://docs.microsoft.com/en-us/windows/wsl/install).

I could also see a case being made about merging both documentations but I know this probably could lead to unneeded confusion. 

I'm not dead set on this suggestion and would love to hear thoughts.

**Comment by jaredcwhite** [comment]
@subsevenx Yeah, I'm totally cool with removing the GoRails links and including more documentation directly in the page…my conundrum is I just don't have a way to test out updated instructions. But if you can clean up the page and vouch for it, I'll happily merge it in.

**Comment by subsevenx** [comment]
@jaredcwhite Apologies for the delay! I'll be working on some drafts this week. I also recorded some videos recently showing the installation process in Windows, which can vouch for the process working :smile:
