### ISSUE TITLE
Fresh install of v.1.0 failing with Ruby 3.0 - * Puma server gem not found

### ISSUE THREAD

**Issue by oleingemann** [bridgetownrb/bridgetown#519]
During a clean install of v.1.0 (with Ruby 3.0 running Ubuntu) I got the error listed below as a result of running 'bridgetown start'.
All the other steps from the 'getting started guide' was completed without any issues.
Note: Both yarn install and bundle install completed without any issues, and Puma is in my gemfile.
When I changed to Ruby 2.7 and ran bundle install and yarn, everything worked as expected.

This is the stacktrace from Ruby 3.0 clean install: 

[Bridgetown]           Starting: Bridgetown v1.0.0 (codename "Pearl")
[Bridgetown]   Exception raised: RuntimeError
[Bridgetown] ** Puma server gem not found. Check your Gemfile and Bundler env? ** 
[Bridgetown]                  1: /home/username/.rvm/gems/ruby-3.0.0/gems/bridgetown-core-1.0.0/lib/bridgetown-core/commands/start.rb:36:in `rescue in start'
[Bridgetown]                  2: /home/username/.rvm/gems/ruby-3.0.0/gems/bridgetown-core-1.0.0/lib/bridgetown-core/commands/start.rb:33:in `start'
[Bridgetown]                  3: /home/username/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
[Bridgetown]                  4: /home/username/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
[Bridgetown]                  5: /home/username/.rvm/gems/ruby-3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:134:in `block in invoke_all'
[Bridgetown]          Backtrace: Use the --trace option for complete information.

**Comment by ayushn21** [comment]
Hey @oleingemann, just wanted to clarify if you ran `bridgetown start` or `bin/bridgetown start`? 

If it was the former, could you please try running `bin/bridgetown start` or `bin/bt start` and check if that works? That will execute the command in the context of your bundle.

**Comment by oleingemann** [comment]
Hey @ayushn21 - That worked. I am closing the issue.
