### ISSUE TITLE
feat: Sass support with esbuild

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#526]
Currently Sass is only supported when the Webpack frontend bundler is used. We should provide it as an option for esbuild as well.

**Comment by jaredcwhite** [comment]
@ayushn21 I appreciate the context there…I think it makes the most sense though to have Sass run within the esbuild process as a plugin, that way Sass files are importable from JS files and in other situations where the bundler's dependency tree is getting established.

In a broader conversation, I can envision down the road offering a "bundler-free" variant of a Bridgetown site setup, but in that case I don't feel the need to support Sass. Just use vanilla CSS for a zero-build-step config.

**Comment by ayushn21** [comment]
> I think it makes the most sense though to have Sass run within the esbuild process as a plugin, that way Sass files are importable from JS files and in other situations where the bundler's dependency tree is getting established.

Yeah that's fair, I did think of that potential use case after posting that comment :)

> I can envision down the road offering a "bundler-free" variant of a Bridgetown site setup, but in that case I don't feel the need to support Sass. Just use vanilla CSS for a zero-build-step config.

Indeed, I agree! 👍
