### ISSUE TITLE
Deploying is overwriting custom domain on GitHub Pages

### ISSUE THREAD

**Issue by scarroll32** [bridgetownrb/bridgetown#529]
**Bridgetown Version**:

bridgetown 1.0.0 "Pearl"

**To Reproduce**

In my [public repo](https://github.com/scarroll32/splitfilter) I am using the example Bridgetown GitHub Actions workflow to deploy. It is all deploying OK, but for some reason the custom domain name is wiped out every time there is a deploy (I just re-add it manually). It seems to be very similar to [this issue](https://github.com/tschaub/gh-pages/issues/213).

**Current behaviour**

Push to the repo and trigger CI -> the custom domain is removed from the Pages config.

**Expected behaviour**

Does not remove the domain.

**Additional context**
I'm using Namecheap to manage the domain.

**Comment by scarroll32** [comment]
Awesome project, by the way 😄

**Comment by johlym** [comment]
Your repo looks like it’s missing a `CNAME` file with the domain in it. Next time you set that, pull the branch and ensure it’s in source control so it persists between deploys.

**Comment by jmarsh24** [comment]
I'm also experiencing this issue on deploy. I think there is an issue with the GitHub build script or I'm missing some sort of configuration.

**Comment by scarroll32** [comment]
I never ended up resolving this, just manually update the config after every deploy. 😢

**Comment by jmarsh24** [comment]
I'm trying to move my deployment to render as @jaredcwhite seems to recommend it.

It's a pretty frustrating issue and I don't see anything in the docs to explain what else needs to be configured.

**Comment by jaredcwhite** [comment]
@scarroll32 @jmarsh24 I'm sorry this has been such a pain. I've created a new issue https://github.com/bridgetownrb/bridgetown/issues/614 to track updating our bundled configuration to support the new, officially sanctioned way of building arbitrary static content with any generator for hosting on Pages. In the meantime, I do think Render is the best (and still free!) alternative.
