### ISSUE TITLE
feat: allow resources/generated pages to be manipulated using DOM-style tooling

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#536]
I'm in a hurry so I'll flesh this out later, but after a chat with @claviska I came up with an idea for providing a way for plugins to hook into a DOM-style representation for HTML content (thinking we'll use Nokogiri for this). Upon post-render (aka after going through template engines, Markdown, etc.), one or more plugins could access the "DOM" and make changes, and after all plugin transformations we'd serialize back to HTML. Some examples:

```ruby
  def build
    inspect_html do |document|
      meta = document.query_selector("head > meta[name='description']")
      meta[:content] = "A whole new description"
    end

    inspect_html do |document|
      footer = document.query_selector(:footer)
      footer[:class] = "cool-footer-class"
    end

    inspect_html do |document|
      document.query_selector_all("upcase-me").each do |el|
        el.content = el.content.upcase
      end
    end
  end
```

**Comment by jaredcwhite** [comment]
Got this working and it's pretty stellar. I'm already using for a build-time way to adding an `#` on hover for headings to permalink to the heading ID. Currently on the Bridgetown site that's done at runtime on the client. Here's the code:

```ruby
inspect_html do |document|
  document.query_selector_all("article h2[id], article h3[id]").each do |heading|
    anchor_link = document.create_element(
      "a", "#",
      href: "##{heading[:id]}",
      class: "heading-anchor"
    )
    heading.add_child document.create_text_node(" ")
    heading.add_child anchor_link
  end
end
```

Also adding a feature where if `bypass_html_inspectors: true` is in a resource's front matter, the whole document parsing step is skipped for performance reasons.

**Comment by jaredcwhite** [comment]
Ooo, this is a fun one. Automatically add `target="_blank"` to outgoing links!

```ruby
inspect_html do |document|
  document.query_selector_all("a").each do |anchor|
    next if anchor[:target]

    next unless anchor[:href]&.starts_with?("http") && !anchor[:href]&.include?(site.config.url)

    anchor[:target] = "_blank"
  end
end
```

**Comment by claviska** [comment]
It isn't public yet, but my Doxicity repo has a similar plugin. It does a tiny bit more (e.g. lets you add an external link icon, customize the target, sets noopener/noreferrer, and appends a class name to each link).

But the gist is the same. Here's the relevant section:

```ts
  return {
    transform: doc => {
      doc.querySelectorAll('a').forEach((link: HTMLAnchorElement) => {
        if (isExternalLink(link)) {
          link.classList.add(opts.className);

          const rel = [];
          if (opts.noopener) rel.push('noopener');
          if (opts.noreferrer) rel.push('noreferrer');

          if (rel.length) {
            link.setAttribute('rel', rel.join(' '));
          }

          if (opts.target) {
            link.setAttribute('target', opts.target);
          }

          if (opts.addIcon) {
            const div = doc.createElement('div');
            div.innerHTML = opts.iconSvg!;
            const svg = div.querySelector('svg')!;
            svg.classList.add(`${opts.className}__icon`);
            link.append(svg);
          }
        }
      });

      return doc;
    }
  };
```

I have a number of plugins like this, and it's so nice to be able to do DOM operations in SSG plugins. 🤯

**Comment by jaredcwhite** [comment]
Looks awesome @claviska. I think this category of plugin opens up a whole new world for what you can do with rendering pipelines and it's one of those things that seems entirely obvious in hindsight. 👍 Certainly aids in shipping a lot less JS to the browser!

**Comment by claviska** [comment]
This idea started as a "why can't I do this" when using 11ty. Many of the plugins, e.g. code highlighting, only work on your markdown so your templates and other code can't use it without calling a separate API (if one exists). IMO, it makes more sense to use their `transform` API, but then _every plugin_ for _every page_ has to:

1. Parse the HTML
2. Load Cheerio or JSDOM or something that can render mutate the HTML
3. Mutate the DOM (or DOM-like thing)
4. Serialize the HTML

This hooks removes that overhead and makes plugins more consistent and easier to write. Now it's just:

1. Mutate a `Document` object and pass it back

IMO this is a superior API for many plugins, although 11ty's `transform` plugin (which operates on the full HTML string) is still useful for things like formatting the outputted code.

**Comment by brandondrew** [comment]
@claviska 

> This idea started as a "why can't I do this" when using 11ty. 

So I imagine this answers the question of "what does Doxicity do that the other JS SSGs don't do?"?

(Of course I prefer to use Ruby, and I'm thrilled that Bridgetown can do this and so many other things, but it's good to keep an eye on what's available in the JS world.)

**Comment by claviska** [comment]
@brandondrew 

> So I imagine this answers the question of "what does Doxicity do that the other JS SSGs don't do?"

That was one pain point I wanted to solve. Others included a documentation-centered theme, the ability to provide global + page-level data, and the ability to use a single, simple template language in markdown.
