### ISSUE TITLE
Error when run `yarn run esbuild-dev`

### ISSUE THREAD

**Issue by work-leonid** [bridgetownrb/bridgetown#543]
**Bridgetown Version**:
bridgetown 1.0.0 "Pearl"

**To Reproduce**
1. Create a new Bridgetown site 
2. Start `bin/bridgetown start`
3. It will show an error. The server still starts, but esbuild doesn't work.

**Expected behavior**
Start without errors and esbuild should work as expected.

**Screenshots**
Terminal
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/8654430/164967838-be82dba9-f956-4cbe-85a5-fb434764adb4.png">

The site looks like this:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8654430/164967885-75216757-d07e-4f2a-95fb-673820588b30.png">

**Computing environment (please complete the following information):**
 - OS: macOS Monterey 12.3.1
 - Ruby Version 3.1.1

**Additional context**
I use `asdf` packet manager.
`asdf current` show
nodejs          17.3.0          /Users/leonix/.tool-versions
postgres        14.1            /Users/leonix/.tool-versions
ruby            3.1.1           /Users/leonix/.tool-versions

**Comment by jaredcwhite** [comment]
@work-leonid What's `.pnp.cjs`? That's not a file we install. Try deleting that and see what happens.

**Comment by work-leonid** [comment]
The `.pnp.cjs` file contains various maps: one linking package names and versions to their location on the disk and another one linking package names and versions to their list of dependencies. It's [from yarn](https://yarnpkg.com/features/pnp). 

To be honest, I don't understand how it got there. Maybe it's an `asdf` problem. But I already install yarn directly and the error still the same. If I delete this file, it appears again after the bridgetown start.

**Comment by jaredcwhite** [comment]
@work-leonid yeah that's odd. `read-cache` is a dependency of `postcss-import` which should be in your `package.json` file, so it should know how to resolve the dependency. Maybe run `yard add -D read-cache` to add it explicitly?

**Comment by jaredcwhite** [comment]
I'll see about adding `read-cache` as an explicit dependency by default…while "classic" Yarn which I use hasn't complained about the issue, it does make sense to include that if it's required directly by the esbuild config file.

**Comment by work-leonid** [comment]
> @work-leonid yeah that's odd. `read-cache` is a dependency of `postcss-import` which should be in your `package.json` file, so it should know how to resolve the dependency. Maybe run `yard add -D read-cache` to add it explicitly?

Sorry for the late response, but this advice helped! Thank you so much!
