### ISSUE TITLE
Allow the Tailwind `jit-refresh.css` to be optional and added to `.gitignore`

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#547]
Currently if the file isn't present on a build, the frontend bundler will crash. But if the file's checked in, it makes branch merges more difficult.

**Comment by eelcoj** [comment]
Just stumbled upon this issue where it crashed. Happy to help (or test) where/if needed.

**Comment by jaredcwhite** [comment]
Fix is now in #559 with info on how to apply the (simple) fix manually to existing projects.

**Comment by eelcoj** [comment]
Just set up—works great! 👍
