### ISSUE TITLE
Post with future date still shown, but return 404

### ISSUE THREAD

**Issue by C-Mejlak** [bridgetownrb/bridgetown#557]
When a post has a future date, it is not being skipped in the `for` loop.

**Bridgetown Version**:

1.0.0

**To Reproduce**

1. Create a new project
```
bridgetown new site
```

2. Change post's filename to a future date
3. Change post's frontmatter date to a future date
4. Start development server
```
bin/bridgetown start
```
5. Navigate to http://localhost:4000/posts

**Current behavior**

"Your First Post On Bridgetown" is present, but returns a 404 

**Expected behavior**

I expect posts with a future date to be skipped. 
Unless `future: true` is set in the configuration.

**Comment by jaredcwhite** [comment]
Thanks @C-Mejlak for the bug report. It looks like we have a lingering issue where future-dated items show up in collection listings but don't get written out during the build process (hence the 404). I'll work on a fix to ensure it's not added at all to the collection (unless future is true).
