### ISSUE TITLE
Add `.gitpod.yml`, GitPod bundled configuration

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#566]
[GitPod](https://www.gitpod.io/) is pretty rad and seems to be a bit ahead of GitHub Codespaces in some ways. I just remote updated some gems and content on a Bridgetown site and previewed it running live—even used Solargraph with Rubocop integration—and it just worked and worked _fast_. All from my iPad Pro!

So (a) it'd be great to add a bundled configuration so any Bridgetown site can add support for GitPod editing, and (b) we should add a `gitpod.yml` to the Bridgetown repo itself and include contributor instructions for how to use GitPod to work on, test, and submit Bridgetown PRs. That way anyone can become a contributor—even if their only computer is an iPad! 😊

FYI:
https://www.gitpod.io/docs/getting-started#open-in-gitpod-button
https://www.gitpod.io/docs/languages/ruby#ruby-versions

**Comment by jaredcwhite** [comment]
Making progress on (b)…

**Comment by creaturenex** [comment]
I would like to give this a try.

**Comment by jaredcwhite** [comment]
It kinda works pretty well out of the box right now, but if there's a mismatch between the default Ruby version on GitPod any `.ruby-version` file, then it's not quite automatic to get started
