### ISSUE TITLE
Configure a _pages directory to store your pages

### ISSUE THREAD

**Issue by kb1995** [bridgetownrb/bridgetown#57]
## Motivation

If you have a lot of pages, it nice to put them under a _pages category like Jekyll does it

## Suggestion

In bridgetown.config.yml, add

```
include: 
  - _pages
```

And then you can create a _pages folder within src directory where you can house all of your pages except the index page. Not sure if it's possible to put the index page within the folder as well?

It could be a good to make this the default within the framework as I think it's a good structure pattern.

**Comment by jaredcwhite** [comment]
Thanks @kb1995! We should definitely document that pattern. I'll look into the idea of making it the default, but it certainly should be an option at least.

**Comment by jaredcwhite** [comment]
Hey @kb1995, I finally got around to this and it actually required a code fix to implement cleanly. If you got a moment to try it out, I'd appreciate the feedback!
