### ISSUE TITLE
feat: Switch to gems.rb and rakefile.rb

### ISSUE THREAD

**Issue by svoop** [bridgetownrb/bridgetown#592]
## Summary

Have the `bridgetown new` command generate different files (with the same content though):

* `Gemfile` -> `gems.rb`
* `Rakefile` -> `rakefile.rb`

## Motivation

Since [Bundler 1.16 paved the way](https://depfu.com/blog/2017/09/06/gemfiles-new-clothes) five years ago, many other gems joined the effort to allow alternative config file names with extensions in order to have proper syntax coloring in editors.

Given the pioneer character of Bridgetown, it's safe to assume that all existing Bridgetown sites will use Bundler >= 1.16. As for Rake, the alternative `rakefile.rb` is supported for more than 10 years already.

And in the worst case, it's always possible to rename the files to their extension-less twins should if your stack for some weird reason depends on it.

**Comment by jaredcwhite** [comment]
Hey @svoop, I could see us switching to `rakefile.rb`, but the `Gemfile/Gemfile.lock` naming is so ingrained in a wide variety of tooling at this point I'd be very hesitate to switch to anything else. I also don't want to violate the "principle of least surprise" — most Rubyists would be quite surprised to open a Ruby project and not see any Gemfile/lock

**Comment by svoop** [comment]
@jaredcwhite

It's kinda bummer that Bundler doesn't promote`gems.rb` more, so at the current pace, you're right about the least surprise. However, the problem is not so much the generated default being `Gemfile` but the binstubs `bin/bridgetown` and `bin/bt` to hardcode `Gemfile`. It should be possible to just rename the `Gemfile`, but this Hardcoding forces you to rebuild the binstubs forcefully after that... based on a somewhat irritating error message.

The former apparently is created by `bundle binstub` and the latter (without looking at your code) seems to just be a copy of that. So I'll try to PR a little addition to Bundler in order to have stubs accept both variations of Gemfiles.

Until then, the way to upgrade a fresh (or existing) Bridgetown site would be:

```
bridgetown new mysite

cd mysite
mv Gemfile gems.rb
mv Gemfile.lock gems.locked
mv Rakefile rakefile.rb
bundle binstub bridgetown-core --path bin --force
cp bin/bridgetown bin/bt
```

**Comment by svoop** [comment]
Just found this old issue, totally forgot about it when I threw together PR #658.

You're right about least surprise, `bridgetown new` should therefore keep creating a `Gemfile`. However, Bridgetown must not break in case the user `mv Gemfile gems.rb`.

Apparently, it doesn't take much to achieve this. For PR #658 I found only two places. (One of which will be history soon since it's related to loading plugins via the `bridgetown_plugins` group.)
