### ISSUE TITLE
docs: Test out Git-based CMSes

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#62]
I'm wondering what, if anything, we'd need to do to ensure NetlifyCMS and Forestry work with Bridgetown sites. Will the reasonably close similarities to Jekyll help us, or hurt us? (maybe they'll just get hopelessly confused?) Need to do some testing, fix any issues, and then write up documentation.

**Comment by jaredcwhite** [comment]
Wow, I ran into a lot of problems trying to test out NetlifyCMS. It basically feels broken unless you're actually using Netlify (in my case I was trying to test with a site hosted by Vercel). Not a great OOTB experience. 😕

**Comment by jaredcwhite** [comment]
There's a real hole in the market if Forestry is the only Git-based CMS approaching anything resembling "insanely great". If I were fishing for a new startup idea…

(Just kidding. I have no interest in running a CMS company. Some open-source Ruby tools however… 🤔🤔🤔)

**Comment by andrewmcodes** [comment]
I've tried them all at this point and unfortunately NetlifyCMS works the best. 

I did get the preview option working on one of my projects somewhere on my computer that I can find if that was one of your complaints about it. 

Not a big fan of it tbh - building the config is a pain and I'm super surprised there hasn't been a lot of movement to build tools to make this process easier.

**Comment by jaredcwhite** [comment]
I really can't in good conscience recommend any Git-based CMSes at the point, which really sucks. Hopefully continuing efforts in 2021 will eventually result in a useable sequence of steps for setting up a decent Rails-based CMS. I continue to resist the notion of outright creating "BridgetownCMS" …but if somebody wants to drop seed money in my lap, I'm not gonna argue. :wink: :wink: :wink:
