### ISSUE TITLE
bug: adding `keep_files: [".git"]` config option prevents `_bridgetown` folder from being created

### ISSUE THREAD

**Issue by whysthatso** [bridgetownrb/bridgetown#624]
when adding this line:
`keep_files: [".git"]`
to bridgetown.config.yml

the subdirectory `_bridgetown` is not being created, and static files are not available. however, there is no error in the log output, esbuild functions normally and creates the files.

**Bridgetown Version**:
1.1.0

**To Reproduce**
- generate vanilla project `bridgetown new demo -t erb`
- add `keep_files: [".git"]` to bridgetown.config.yml
- run `bin/bt start`
- confirm folder  `_bridgetown` is not existing
- confirm log shows no errors

**Log output**
```
[Bridgetown]           Starting: Bridgetown v1.1.0 (codename "Belmont")
[Server] * Puma version: 5.6.4 (ruby 3.1.2-p20) ("Birdie's Version")
[Server] * PID: 11501
[Server] * Listening on http://0.0.0.0:4001
[Server] Use Ctrl-C to stop
[Frontend] yarn run esbuild-dev
[Frontend] yarn run v1.22.19
[Frontend] $ node esbuild.config.js --watch
[Frontend] esbuild: frontend bundling started...
[Bridgetown]        Environment: development
[Bridgetown]             Source: /home/andreas/resilio/projects/wellpress_site/bulma_fresh/src
[Bridgetown]        Destination: /home/andreas/resilio/projects/wellpress_site/bulma_fresh/output
[Bridgetown]     Custom Plugins: /home/andreas/resilio/projects/wellpress_site/bulma_fresh/plugins
[Bridgetown]         Generating… 
[Frontend] esbuild: frontend bundling complete!
[Frontend] esbuild: entrypoints processed:
[Frontend]          - index.CY6HFAGO.js: 238.89KB
[Frontend]          - index.OKYRN2M2.css: 279.83KB
[Bridgetown]         Pagination: disabled. Enable in site config with pagination:\n enabled: true
[Bridgetown]             Done! 🎉 Completed in less than 0.55 seconds.
[Bridgetown]                     
[Bridgetown]     Now serving at: http://localhost:4000
```
**Computing environment (please complete the following information):**
 - OS: linux
 - Ruby Version: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]

**Comment by jaredcwhite** [comment]
Ran into this again, looks like we need to merge `_bridgetown` into whatever custom setting a user might specify.
