### ISSUE TITLE
docs: Listed minimum node version not supported

### ISSUE THREAD

**Issue by jake-duchesne** [bridgetownrb/bridgetown#631]
## Motivation

Ran into an issue with requirements while trying out Bridgetown on a fresh install. The docs mention needing "Node version 12 or above (which you can check by running node -v)" but during fresh install I encountered this error with `node v12.2.22`

```
yarn install v1.22.17
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error @csstools/postcss-trigonometric-functions@1.0.2: The engine "node" is incompatible with this module. Expected version "^14 || >=16". Got "12.22.12"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
       alert  Could not load yarn. yarn install skipped.
```

The docs suggest that a node version of 12 is sufficient to install Bridgetown but it seemingly needs v14 or greater than v16.

## Suggestion

Update the recommended node version to at least v16 or above.

**Comment by jake-duchesne** [comment]
Picking up this issue to give it a try 👍🏻

**Comment by jaredcwhite** [comment]
We'll be making a big swing to minimum Node v20 support for Bridgetown v2.
