### ISSUE TITLE
docs: switch from `master` to `main` when relevant in the documentation

### ISSUE THREAD

**Issue by Dynnammo** [bridgetownrb/bridgetown#642]
## Motivation

As it is specified multiple time in the CHANGELOG, Github and GitLab are using now `main` as the name of the default branch. However, I see numerous times that the `master` branch is still quoted (as instance in deployment documentation : https://www.bridgetownrb.com/docs/deployment)

## Suggestion

Replace with `main` whenever possible. I can make a PR about it, since it doesn't seem to be huge as a change.

**Comment by ayushn21** [comment]
Yeah if you'd like to make a PR, go for it!

We use `main` as the default branch for the Bridgetown project as well as all new Bridgetown sites. The use of `master` in docs is outdated. Thanks for flagging this.
