### ISSUE TITLE
bug: Update Deployment to Gitlab with `.gitlab-ci.yml`

### ISSUE THREAD

**Issue by Dynnammo** [bridgetownrb/bridgetown#643]
## Motivation

Hey there ! I had multiple errors to solve in order to deploy Bridgetown on GitLab Pages : 

- [ ] version of Node specified in the example file in the doc is `12.x`. However current verison of node is 16. It triggers error at compilation. Quick fix is to modify it directly. Good fix would be to detect latest node version available
- [ ] `yarn webpack --mode production` doesn't work first, since the `package.json` does not contain it . Quick fix is to run `yarn add webpack webpack-cli` in the `gitlab-ci.yml`. Good fix to determine
- [ ] After being installed, `yarn webpack --mode production` doesn't succeed. Returns me the following error : 
```
ERROR in main
Module not found: Error: Can't resolve './src' in '/home/baptiste/Documents/blog2'
resolve './src' in '/home/baptiste/Documents/blog2'
  using description file: my/path/to/site/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: my/path/to/site/package.json (relative path: ./src)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        my/path/to/site/src is not a file
      .js
        Field 'browser' doesn't contain a valid alias configuration
        my/path/to/site/src.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        my/path/to/site/src.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        my/path/to/site/src.wasm doesn't exist
      as directory
        existing directory my/path/to/site/src
          using description file: my/path/to/site/package.json (relative path: ./src)
            using path: my/path/to/site/src/index
              using description file: my/path/to/site/package.json (relative path: ./src/index)
                no extension
                  Field 'browser' doesn't contain a valid alias configuration
                  my/path/to/site/src/index doesn't exist
                .js
                  Field 'browser' doesn't contain a valid alias configuration
                  my/path/to/site/src/index.js doesn't exist
                .json
                  Field 'browser' doesn't contain a valid alias configuration
                  my/path/to/site/src/index.json doesn't exist
                .wasm
                  Field 'browser' doesn't contain a valid alias configuration
                  my/path/to/site/src/index.wasm doesn't exist

webpack 5.74.0 compiled with 1 error in 77 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

## Suggestion

Available to peer-prog or give some insights about it, I know this issue might sound a bit harsh, but I swear (contrary to Marauder Map's use) that my intents aren't evil, and I would be pleased to use Bridgetown for my personal blog if I suceed to :sob:

**Comment by jaredcwhite** [comment]
@Dynnammo  I don't use GitLab, so it's hard for me to know how to resolve this. Would you be willing to submit a PR to update the documentation? Also we shouldn't be encouraging people to use Webpack anymore, we've standardized around esbuild now.

**Comment by Dynnammo** [comment]
I'll do my best :raised_hands:
