### ISSUE TITLE
Data builder example broken

### ISSUE THREAD

**Issue by svoop** [bridgetownrb/bridgetown#669]
The [edge example to add data from API calls](https://edge.bridgetownrb.com/docs/plugins/external-apis#making-a-request) appears to be broken. 

In my site, I'm building a collection of aeronautical regions:

```ruby
class Builders::OfmApiResources < SiteBuilder
  RESOURCES = {
    regions: "shortName"
  }

  def build
    RESOURCES.each do |resource, key|
      OfmApi.send(resource).each do |data|
        site.data[resource] = data.last.to_h { [_1[key], _1] }.sort
      end
    end
  end
end
```

Stripped down, this essentially assigns:

```ruby
site.data[:region] = { "LF" => { "name" => "France" } }
```

In the `bridgetown console`, I'd expect this key to be present in `site.data`, however, it's not:

```ruby
site.data.keys   # => ["site_metadata"]
```

Apparently, either the builder example in the edge docs is out of date or something else is broken on the way to 1.2... or I'm misreading the docs. :wink:

**Bridgetown Version**: 

bridgetown 1.2.0.beta4 "Bonny Slope"

**Computing environment (please complete the following information):**
 - OS: macOS 13.0.1
 - Ruby Version: 3.1.3

**Comment by jaredcwhite** [comment]
@svoop Hmm, I wonder if that example would need to be wrapped inside of a `post_read` hook, ala: https://edge.bridgetownrb.com/docs/plugins/external-apis#builder-lifecycle-and-data-files

Can you try that and let me know if it fixes the issue?

**Comment by jaredcwhite** [comment]
@svoop good call, I've added that to the docs.
