### ISSUE TITLE
Improve international character support in slugify

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#67]
While we're not routinely tracking low-level Jekyll improvements at this point, occasionally something might catch my eye and this is one of them:

https://github.com/jekyll/jekyll/pull/8167

Seems like something important to improve here as well.

**Comment by ParamagicDev** [comment]
I'm all for additional i18n support. I'll take a look at the Jekyll PR and see if it could be simply dropped into Bridgetown. 

I also don't think there's enough people using Bridgetown to worry about extreme-edge cases that this may be break as mentioned in the Jekyll issue.
