### ISSUE TITLE
key `locales' not found in attributes for new Bridgetown::Model::Base

### ISSUE THREAD

**Issue by Jahija303** [bridgetownrb/bridgetown#681]
This appears when using multi locale files, either by naming the file with .multi.md extension (eg: index.multi.md) or adding "locale: multi" to front matter (docs: https://www.bridgetownrb.com/docs/internationalization#multi-locale-files). 
It does not show up otherwise, eg: having two separate files and naming them index.en.md, index.de.md.

**Bridgetown Version**:
1.2.0.beta4

**To Reproduce**
Set "locale: multi" in front matter
OR
Use the .multi extension within the file name

- source: https://www.bridgetownrb.com/docs/internationalization#multi-locale-files

**Current behavior**
Logs: "key `locales' not found in attributes for new Bridgetown::Model::Base"

**Expected behavior**
Do nothing

**Computing environment (please complete the following information):**
 - OS: Ubuntu 22.04.1
 - Browser: Brave 1.145.133
 - Ruby: 3.1.1

**Comment by mattiasamilon** [comment]
I seem to have the same problem, using the `multi` file extension.

**Comment by rickychilcott** [comment]
Can you give the full file name you are using and possibly a reproduction repo? I’m using multi locale via extension and front matter in my project on beta5

**Comment by Gusser93** [comment]
Seems to be this [line](https://github.com/bridgetownrb/bridgetown/blob/e535c9c93c3454d7188ac39294b75fd3497635e6/bridgetown-core/lib/bridgetown-core/collection.rb#L285) causing the message if no locales-attribute is defined in the frontmatter. But I don't have any experience with ruby. My example:

index.md (generates message)
```md
---
layout: default
locale: multi
---

# Welcome to your new Bridgetown website.

{{ "welcome.intro" | t}}
```


index.md (no message)
```md
---
layout: default
locale: multi
locales:
    - de
    - en
---

# Welcome to your new Bridgetown website.

{{ "welcome.intro" | t}}
```

**Comment by jaredcwhite** [comment]
Thanks for the additional context. I'm not sure there's any bug here…it may just be a warning which we could suppress because it's an optional key.
