### ISSUE TITLE
URL does not change to localhost in development when using initializers

### ISSUE THREAD

**Issue by michaelherold** [bridgetownrb/bridgetown#684]
**Bridgetown Version**: bridgetown 1.2.0.beta4 "Bonny Slope"

**To Reproduce**

See [this repository](https://github.com/michaelherold/bt_initializer_bug) for a reproduction.

Manual steps:

1. Set `url: "https://example.com"` in `bridgetown.config.yml`
2. Start the development server with `bin/bt dev`
3. Use `page.relative_url | absolute_url` in a page and see that it's `http://localhost:4000`
4. Stop the development server and modify `config/initializers.rb` with `url "https://example.com"`
5. Restart the development server with `bin/bt dev`
6. Use `page.relative_url | absolute_url` in a page and see that it's now `https://example.com`

**Current behavior**

When using `config/initializers.rb` to set the `url` property for the site, it does not get overridden in development to `http://localhost:4000`.

**Expected behavior**

The `url` property should be overridden locally just like when you set `url` via `bridgetown.config.yml`.

**Computing environment (please complete the following information):**

 - OS: macOS 12.3.1
 - Browser:] Firefox
 - Browser Version: 102.1
 - Ruby Version: 3.1.2

**Additional context**

This is a useful feature that seems like it should work when set via an initializer too. Perhaps this is intended behavior, but it seems preferable to be able to get rid of `bridgetown.config.yml` entirely and configure your site from `config/initializers.rb` without regressions.

**Comment by jaredcwhite** [comment]
Fixed with #686
