### ISSUE TITLE
Bridgtown-Core depends on depreciated Terminal-Table V1

### ISSUE THREAD

**Issue by topofocus** [bridgetownrb/bridgetown#693]
If a Gem, like ib-ruby, is required, a strange incompatibility warning appears and the terminal output of the included program is broken because only the outdated version is loaded.

**Bridgetown Version**:  1.2 beta4

**To Reproduce**
gem dep | grep terminal  

I need to include the ib-ruby-gem, which depends on the actual version of TerminalTable (V 3.02)

Bridgetown-Core uses the outdated  Version1.8 

Is it possible to update the dependencies in Bridgetown to the Version 3 of the TerminalTable Gem?

**Comment by jaredcwhite** [comment]
I can remove that dependency entirely for Bridgetown 1.2 and make it opt in. It's only used in one specific place for debugging purposes (profiling Liquid template usage)

**Comment by topofocus** [comment]
I would appreciate that.
