### ISSUE TITLE
Upgrade Esbuild to v0.17

### ISSUE THREAD

**Issue by xdmx** [bridgetownrb/bridgetown#697]
**Bridgetown Version**: 1.2.0 beta5

Bridgetown is currently using Esbuild 0.16.x, it'd be nice to upgrade to v0.17. It has some breaking changes (eg. the `--watch`): https://github.com/evanw/esbuild/releases/tag/v0.17.0

**Comment by sandstrom** [comment]
I think this comment is relevant to the relationship between JS tooling and Bridgetown:

https://github.com/bridgetownrb/bridgetown/issues/609#issuecomment-1221277335

**Comment by jaredcwhite** [comment]
@sandstrom Not exactly. We'll continue to preference esbuild as our default CSS/JS pipeline. (And we'll likely remove Webpack altogether in Bridgetown 2.0.) I think #609 is more about offering support for a wider range of primarily package managers (NPM vs. Yarn vs. pnpm vs. ?). We also want the option of forgoing any JS-based pipeline (see #720).

**Comment by sandstrom** [comment]
@jaredcwhite Yes, you are right! I agree with everything in the sentence above.

**Comment by jaredcwhite** [comment]
Note: test out with esbuild's latest support for converting native CSS nesting: https://github.com/evanw/esbuild/releases/tag/v0.17.19

**Comment by sandstrom** [comment]
@jaredcwhite Great! The new native CSS nesting is awesome. One of the few things still missing in CSS, that SCSS/SASS had. 

We've actually already started using it, via a postCSS plugin, but even better with direct support in esbuild.
