### ISSUE TITLE
Switch to ERB as the default templating language

### ISSUE THREAD

**Issue by ayushn21** [bridgetownrb/bridgetown#705]
## Summary

I'd like to petition changing the default templating language to ERB for v2.0.

## Motivation

ERB is way more flexible and feature rich. The primary motivation for Liquid in my mind is security in user-authored templates. That's not the case with Bridgetown sites which will almost always be completely authored by the developer.

Features like Bridgetown components are also only available in ERB/Tilt-based templates.

I think using Liquid as the default is a remanent of the Jekyll era and I'd like to petition we change the default to ERB while still retaining Liquid support for people who want to use it!

**Comment by joemasilotti** [comment]
I'm all in favor of moving the default to ERB. That seems to be a better standard moving forward for such a rich tool.

But I still use Liquid for blog posts. And I really don't want to convert 50+ of them to ERB. So, as you mentioned, please don't drop Liquid support even if it isn't the default!

**Comment by ayushn21** [comment]
Definitely no plans to drop Liquid, that would be far too disruptive. We'll always keep it as an option.

**Comment by rickychilcott** [comment]
I started my website in liquid, then dabbled with serbea, and then went to ERB. All have pros and cons, but for my team and most rails/roda converts, they're likely to expect ERB as the default.

**Comment by adrianvalenz** [comment]
ERB as a default sounds great to me! I totally agree about Liquid being a tool to provide protection from authors or template developers such as Shopify originally intended it for. My vote for the full power of Ruby.
