### ISSUE TITLE
Trailing Slash System?

### ISSUE THREAD

**Issue by KorbsStudio** [bridgetownrb/bridgetown#709]
Our company website was recently updated to have all pages not end with a `/` in the URL. 
This is because our CEO wanted to improved the SEO for Microsoft Bing, and Bing doesn't like `/` at the end apparently.

However, this has caused some issues, like old links in Discord that will contain the ending `/` and not working anymore.

Example, https://falixnodes.net/help/ won't work, but https://falixnodes.net/help does work.

___

The website source code is closed sourced to prevent clone sites of FalixNodes and to prevent scammers making a fake FalixNodes website to steal information.

**Comment by jaredcwhite** [comment]
This is a hosting-level concern. I'm not sure what it is you think is a Bridgetown bug.
