### ISSUE TITLE
Deprecation warning for Bundler.with_clean_env

### ISSUE THREAD

**Issue by ParamagicDev** [bridgetownrb/bridgetown#71]
**Bridgetown Version**:
0.15.0.beta2

**To Reproduce**

`bundle exec bridgetown new newsite
`
**Current behavior**

Provides the following warning:

```bash
[DEPRECATED] `Bundler.with_clean_env` has been deprecated in favor of 
`Bundler.with_unbundled_env`. If you instead want the environment before bundler was originally loaded, use `Bundler.with_original_env` 
(called at /home/krog/.gem/ruby/2.6.3/gems/bridgetown-core-
0.15.0.beta2/lib/bridgetown-core/commands/new.rb:118)
```

**Computing environment (please complete the following information):**
 - OS: `ubuntu 20.04`
 - Ruby Version `2.6.3`

**Additional context**

Its only a deprecation warning, can easily be fixed, but wanted to submit an issue before making a PR.

**Comment by jaredcwhite** [comment]
@ParamagicDev I seem to recall that's a warning from Bundler 2.x, but Bundler 1.x doesn't have a `with_unbundled_env` method to the best of my knowledge. Hoping not to require Bundler 2.0+ just yet, lots of folks are still using 1.x (including myself in most environments).

**Comment by ParamagicDev** [comment]
That's exactly what it is. Just wanted to throw it out there so you were aware!
