### ISSUE TITLE
Configuration options not set by init in initializers.rb

### ISSUE THREAD

**Issue by fbuys** [bridgetownrb/bridgetown#716]
**Bridgetown Version**: bridgetown 1.2.0 "Bonny Slope"      

**To Reproduce**

- Add config to initializers.rb
- Start app or Run tests
```ruby
# initializers.rb
  init :sample_plugin do
    Bridgetown.logger.info 'sample initializer...'
    my_setting "test-config-option"
  end
```

- Here is repo (branch: `initializers-issue`): https://github.com/fbuys/bridgetown-sample-plugin/tree/initializers-issue
- Clone repo and checkout `initializers-issue` branch
- `bundle install` and then run `rake test`

**Current behavior**

- Notice that config options are not passed to the plugin initializer
- But the init params are set on the config object

Inside the plugin initializer I am outputting like this:
```ruby
  pp config.to_h
  print "sample_plugin config: " 
  pp config.sample_plugin
```

```shell
...[rest of config object],
 "init_params"=>{"sample_plugin"=>{"my_setting"=>"test-config-option"}},
 "sample_plugin"=>{}}
sample_plugin config: {}
```

**Expected behavior**

I would like to access the config options set in the app initializer.

```ruby
  print "sample_plugin config: " 
  pp config.sample_plugin
```
should output:
```shell
sample_plugin config: { my_setting: "test-config-option" }
```

**Computing environment (please complete the following information):**
 - OS: [e.g. iOS] MacOS
 - Browser [e.g. chrome, safari] n/a
 - Browser Version [e.g. 22] n/a
 - Ruby Version (check with ruby -v) ruby 3.0.1p64 or ruby 3.1.2p20

**Comment by jaredcwhite** [comment]
@fbuys I think you'd need to add `my_setting` as a keyword argument to your initializer for this to work: https://github.com/fbuys/bridgetown-sample-plugin/blob/47f37124f50c81b964c52ba8a981e0f398cda411/lib/sample_plugin.rb

There's probably somewhere in the documentation we should illustrate this more clearly. Also it's best to keep `my_setting` as an optional kwarg (aka default to nil or some value) unless you absolutely need it.

**Comment by fbuys** [comment]
Hey I pushed a PR that might be helpful.
