### ISSUE TITLE
Generate an error page when there is an exception in a page

### ISSUE THREAD

**Issue by MaxLap** [bridgetownrb/bridgetown#718]
## Summary

This could be considered a bug or a feature.

While the server is running (using `start`), if you add a markdown file with an error (in it's ERB in my case) or edit a file to add an error, the only thing that happens is that the error is output to the console.

When browsing, there is no feedback at all. The page isn't changed what so ever. This can be quite confusing for newcomers.

The doing nothing of right now means:
* If the page never existed, you get a 404.
* If the page existed before, you see an older version of the page

If the user reboots his server, the server won't accept to run. That's good enough to avoid confusion in that case.

The most basic improvement I would suggest is generating a simple HTML that says "There was a problem rendering this page, please see logs in your terminal's console". 

## Motivation

As a new users that does web dev, it's easy to expect that if there is a problem, the website itself will give you at least a tiny hint other than "doing nothing".

## Reference-level explanation

When there is an error generating a page, a page should still be generated that says "There was a problem rendering this page, please see logs in your terminal's console". Or some variation based on if you are running a server or building.

This may already exist in some case, but on my basically brand new 1.2.0 installation, it didn't happen when I added a `src/explanations/overview.md` file that had broken ERB. All I kept getting is a 404.

## Drawbacks

I can't think of a reason not to do this.

**Comment by jaredcwhite** [comment]
Thanks @MaxLap. This may prove to be challenging to implement because (_waves hands_) reasons, but you're absolutely right that this experience is subpar. Let's prioritize this for the next release.
