### ISSUE TITLE
feat: Stop dangling process when restarting after a crash

### ISSUE THREAD

**Issue by goulvench** [bridgetownrb/bridgetown#740]
## Summary

When Bridgetown crashes, the port remains open and assigned to the crashed process. Offering to stop the process currently using the port would make restarting much smoother.

## Reference-level explanation

- During start, check the port for availability.
- If it is taken, prompt to either:
  - stop the process, or
  - choose another port (by printing instructions on how to do that)
 
## Unresolved Questions

I'm on a Mac, and I don't know if/how that would work on Windows boxes.

**Comment by brandondrew** [comment]
I wish Rails would also do this after crashing!  I have to have an alias that does the following:

```
kill -9 $(ps aux | grep "puma" | grep -v grep | awk "{ print $2 }") 2&> /dev/null; rm tmp/pids/server.pid 2&> /dev/null;  sleep 3; rails server --port=$PORT
```

**Comment by goulvench** [comment]
Thanks @brandondrew.

I went the rake route and added the following to my `Rakefile`:

```ruby
desc "Kill dangling process"
task :kill do
  port = 4000
  pid = `lsof -i :#{port} -t`.split("\n")&.first
  if pid
    puts "Killing dangling process #{pid}"
    `kill #{pid}`
  else
    puts "No dangling process found"
  end
end
```

**Comment by andreimoment** [comment]
On MacOS, When I run `bridgetown start` more than once (sometimes I exit and start it again) , I see that the puma process was not stopped.

>bridgetown start
[Bridgetown]           Starting: Bridgetown v1.3.4 (codename "Kelly Butte")
[Server] * Puma version: 6.4.2 (ruby 3.3.0-p0) ("The Eagle of Durango")
[Server] * PID: 16351
/Users/andrei/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/puma-6.4.2/lib/puma/binder.rb:334:in `initialize': Address already in use - bind(2) for "0.0.0.0" port 4000 (Errno::EADDRINUSE)

Also, after exiting bridgetown, port 4000 remains occupied and puma continues running.
