### ISSUE TITLE
ERB templates and code blocks

### ISSUE THREAD

**Issue by eclectic-coding** [bridgetownrb/bridgetown#757]
**Bridgetown Version**:
`bridgetown 1.2.0 "Bonny Slope"`

**To Reproduce**
- Spin up a new site: 
`bridgetown new my_site -t erb -c turbo,bt-postcss,render,minitesting --use-sass`
- Added a MD article from a previous site that included the following code block:
```html
  <button class="<%= 'cursor-not-allowed' if logged_in? %>">
```

**Current behavior**
When I spin up the server, it fails with a undefined methos error on `logged_in?`, The ERB template seems ti be evaluating the expression

<img width="967" alt="Screenshot 2023-05-05 at 7 03 48 PM" src="https://user-images.githubusercontent.com/13651291/236582565-b010248c-7d06-4216-8e8d-77b0ed5908cc.png">

**Expected behavior**
I spun up a different site using the default liquid template and everything works fine.

**Computing environment (please complete the following information):**
 - OS: macOS Ventura 13.3.1(a)
 - Browser: Firefox 112.0.2
 - Ruby Version: 3.1.3

**Comment by jaredcwhite** [comment]
@eclectic-coding Yeah, the ERB code is being evaluation within the Markdown file. You'd need to use double-percent signs to escape ([see docs here](https://www.bridgetownrb.com/docs/template-engines/erb-and-beyond#usage)), or you could set `template_engine: none` in the front matter. (I think that's right…going on memory here.)

**Comment by eclectic-coding** [comment]
I will give it a try in the AM. 
just surprised me.
