### ISSUE TITLE
Upgrade to esbuild 0.19.x

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#775]
Time waits for no web developer, and esbuild is already on its 0.18 line. I'm OK with shipping v1.3 with 0.17.x, but I want to immediately follow up with testing support for 0.18.x in a point release.

**Comment by michaelherold** [comment]
For what it's worth, esbuild 0.19.2 runs well on my Bridgetown site. I'm not doing much to exercise it, but 0.18.x and 0.19.x both have primarily breaking changes around the handling of `tsconfig.json`, which shouldn't affect Bridgetown all that much.

**Comment by jaredcwhite** [comment]
@michaelherold Ah, that's good to know.
