### ISSUE TITLE
can not find the pages the link references when using link tag within SSR routes

### ISSUE THREAD

**Issue by bugthing** [bridgetownrb/bridgetown#780]
When using `link` tag within pages built via an SSR route can not find the pages the link references

**Bridgetown Version**:
1.2.0 and 1.3.0

**To Reproduce**
1. gem exec bridgetown new my_site
2. cd my_site
3. edit Gemfile and enable bridgetown-routes
4. edit config/initializers.rb enable ssr and bridgetown-routes
5. cp server/routes/hello.rb.sample server/routes/hello.rb
6. edit hello.rb to read:

```
class Routes::Hello < Bridgetown::Rack::Routes
  route do |r|
    # route: GET /hello/:name
    r.get "hello", String do |name|
        Bridgetown::Model::Base.find("repo://pages/404.html")
          .render_as_resource
          .output
    end
  end
end
```

8. edit `src/404.html` to include `<a href='{% link index.md %}'>home</a>`
9. start bridgetown `./bin/bt start`
10. visit: http://0.0.0.0:4000/hello/test

**Current behavior**
Shows an error message

```
ArgumentError at /hello/test
Could not find document 'index.md' in tag 'link'. (ArgumentError) Make sure the document exists and the path is correct. raise ArgumentError
```

**Expected behavior**
To be shown the 404 page with a link to the index page

**Computing environment:**
 - OS: Linux
 - Browser: firefox
 - Browser Version 115.0.1
 - Ruby Version: 3.2.2

**Comment by jaredcwhite** [comment]
Collections aren't read by default in SSR mode, so you would have to read a collection in manually for this to work, e.g. in the initializer:

```rb
init :ssr do
    setup -> site do
      site.collections.pages.read
    end
  end
```

**Comment by jaredcwhite** [comment]
I'll file a new issue to add this to the Roda documentation.
