### ISSUE TITLE
Unable to access frontmatter array

### ISSUE THREAD

**Issue by crespire** [bridgetownrb/bridgetown#815]
**Bridgetown Version**:

Version 1.3.1

**To Reproduce**

Repository: https://github.com/crespire/portfolio-v2

Steps to Reproduce
1. Build site successfully.
2. Edit `project_card.erb` on line 5 to remove safe navigation, and there will be an error.

**Current behavior**

Bridgetown throws an error on live reload, and logs show:
```
[Bridgetown]    Component error: ProjectCard encountered an error while rendering `/home/crespire/repos/projects/portfolio-v2/src/_components/project_card.erb'
[Bridgetown]   Conversion error: Bridgetown::Converters::ERBTemplates encountered an error while converting `projects.md'
[Bridgetown]   Exception raised: NoMethodError
[Bridgetown] undefined method `each' for nil:NilClass 
[Bridgetown]                  1: /home/crespire/repos/projects/portfolio-v2/src/_components/project_card.erb:5:in `__tilt_8580'
[Bridgetown]                  2: /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/tilt-2.3.0/lib/tilt/template.rb:207:in `bind_call'
[Bridgetown]                  3: /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/tilt-2.3.0/lib/tilt/template.rb:207:in `evaluate'
[Bridgetown]                  4: /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/tilt-2.3.0/lib/tilt/template.rb:102:in `render'
[Bridgetown]                  5: /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bridgetown-core-1.3.1/lib/bridgetown-core/component.rb:197:in `template'

```

**Expected behavior**

Array should be iterable without any issues. 

**Screenshots**

![image](https://github.com/bridgetownrb/bridgetown/assets/36272822/617dd55d-2d31-471d-a720-efe0a752bd10)

**Computing environment (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser: Chrome, but also in Firefox
 - Browser Version: 117.0.5938.92 / 118.0.1
 - Ruby Version: 3.2.2

**Additional context**

I was not able to reproduce this error with a new project. When I initially started the project, I was using Liquid, but then re-ran (using `-f`) bridgetown with `-t=erb` and overwrote the entire directory. Might this have caused an issue?

I am 100% sure this is some issue with my setup and would appreciate a set of eyes on this. I was not able to reproduce the error with a fresh ERB site, and was not able to reproduce with a fresh Liquid site as well.

**Comment by crespire** [comment]
I am 100% sure this is some issue with my setup and would appreciate a set of eyes on this. I was not able to reproduce the error with a fresh ERB site, and was not able to reproduce with a fresh Liquid site as well.

**Comment by crespire** [comment]
Playing around a bit more, I am getting this error also in the console:

```
irb(main):006:1* collections.projects.each do |project|
irb(main):007:1*   project.data.tech.each { |tech| puts tech }
irb(main):008:0> end
Ruby on Rails
Hotwire                                                                                               
React                                                                                                 
Typescript                                                                                            
(irb):7:in `block in <top (required)>': undefined method `each' for nil:NilClass (NoMethodError)      
        from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bridgetown-core-1.3.1/lib/bridgetown-core/collection.rb:54:in `each'
        from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bridgetown-core-1.3.1/lib/bridgetown-core/collection.rb:54:in `each'
        from (irb):6:in `<main>'                                                                      
        from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bridgetown-core-1.3.1/lib/bridgetown-core/commands/console.rb:116:in `block in console'
        from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bridgetown-core-1.3.1/lib/bridgetown-core/commands/console.rb:109:in `catch'
        from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/bridgetown-core-1.3.1/lib/bridgetown-core/commands/console.rb:109:in `console'
        from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
        from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:134:in `block in invoke_all'
	from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:134:in `each'
	from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:134:in `map'
	from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:134:in `invoke_all'
	from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/group.rb:232:in `dispatch'
	from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/invocation.rb:116:in `invoke'
	from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor.rb:40:in `block in register'
	from /home/crespire/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	... 6 levels...
```

**Comment by jaredcwhite** [comment]
@crespire it looks like you don't have a `tech` variable on some of your projects, so that's why you're getting the error. Either you would need to make sure that array is present on every project, even if it's empty, or you'll need to use the safe navigation operator or some other way of avoiding a `nil` bug.

Let me know if that makes sense!

**Comment by crespire** [comment]
> @crespire it looks like you don't have a `tech` variable on some of your projects, so that's why you're getting the error. Either you would need to make sure that array is present on every project, even if it's empty, or you'll need to use the safe navigation operator or some other way of avoiding a `nil` bug.
> 
> Let me know if that makes sense!

Oh lord, yes that makes total sense! Jeeze, what a rookie mistake! I think the Rails "model" mental model is leaking through here causing a blind spot, thank you!
