### ISSUE TITLE
esbuild can't import scss files from node_modules

### ISSUE THREAD

**Issue by DEfusion** [bridgetownrb/bridgetown#831]
**Bridgetown Version**: bridgetown 1.3.1 "Kelly Butte"

**To Reproduce**

1. `bridgetown new foo --use-sass`
2. `yarn add normalize-scss`
3. Add `@import "normalize";` to `frontend/styles/index.scss`
4. `yarn esbuild`

**Current behavior**
It does not compile, with the following error:

```
✘ [ERROR] Can't find stylesheet to import.
  ╷
1 │ @import "normalize";
  │         ^^^^^^^^^^^
  ╵
  frontend/styles/index.scss 1:9  root stylesheet [plugin sass]

    frontend/javascript/index.js:1:7:
      1 │ import "$styles/index.scss"
        ╵        ~~~~~~~~~~~~~~~~~~~~

  This error came from the "onLoad" callback registered here:

    config/esbuild.defaults.js:151:10:
      151 │     build.onLoad({ filter: /\.(sass|scss)$/ }, async (args) => {
          ╵           ~~~~~~

    at setup (foo/config/esbuild.defaults.js:151:11)
    at handlePlugins (foo/node_modules/esbuild/lib/main.js:1292:21)
```

I could get around it by changing the import to `@import "../../node_modules/normalize-scss/sass/normalize";` however the actual package I'm having trouble with is a private package which itself also imports SCSS from other packages so that is not an option here.

**Expected behavior**

It should compile.

**Computing environment (please complete the following information):**
 - OS: MacOS
 - Browser: N/A
 - Ruby Version: 3.1.1

**Comment by jaredcwhite** [comment]
Can you try `@import "normalize-scss/sass/normalize";`? It's unclear to me if there's any sort of standard Node package resolution that would actually support just `@import "normalize";`

**Comment by jaredcwhite** [comment]
Closing out, not sure what the issue was.
