### ISSUE TITLE
docs: show how to read collections in SSR mode

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#840]
The SSR / Roda docs are currently lacking information about how to read collections in manually. For example, something like this in an initializer:

```rb
  init :ssr do
    setup -> site do
      site.collections.pages.read
      site.collections.some_other_collection.read
    end
  end
```

Collections aren't loaded by default for performance/memory reasons. We might want an omnibus "read all collections" option though just in case folks are willing to take the performance hit.

**Comment by jclusso** [comment]
I ran into this personally so I definitely think docs could be stronger here!

**Comment by jaredcwhite** [comment]
in v2 we'll have an "inverted" config where collections are all read in by default and there's a per-collection opt-out possibility for performance reasons…will be documented, so closing this one out.
