### ISSUE TITLE
Class map for Liquid components

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#86]
By far the messiest code pattern I've seen while working on Liquid components and templates in general is constructing a string of CSS class names based on incoming variables. Typically in frontend component libraries you'll see a "class map" function that makes this process pretty straightforward. Prior art:

* https://lit-html.polymer-project.org/guide/styling-templates
* https://github.com/JedWatson/classnames

It would be great to have a Liquid tag to make this easy. Something like:

```
<button class="{% class_map is-small: small, has-text-center: centered, outlined: !filled %}">…</button>
```

We'd have to do some fancy parsing to load variables from local scope and work with conditional values, but the actual business of constructing the output string should be pretty easy.

I'm also tempted to make this its own little gem so it can be used anywhere, but maybe we can implement here first and extract it out at some point once it's working well.

**Comment by ParamagicDev** [comment]
So basically class_map takes in a hash, the key is the class, and value is Boolean. If the Boolean is true, then output the key, if the Boolean is false, ignore the key.

Rough example:
  Input:

```
<button class="{% class_map text-center: true, bg-red-500: "string", shadow: false %}">I'm a button</button>
```
 
 Output:

```
<button class="text-center bg-red-500">I'm a button</button>
```

**Comment by jaredcwhite** [comment]
Added in #99
