### ISSUE TITLE
feat: Generate README when running bridgetown new

### ISSUE THREAD

**Issue by andrewmcodes** [bridgetownrb/bridgetown#87]
## Summary

Right now when you run `bridgetown new mysite`, a new site is created, but it does not have a README. I consider a README to be something almost everyone will add to their project, so it would be great is `Bridgetown new` created it for you.

## Motivation

Laziness to be honest, but I think it will collectively save many time and also encourage projects to have a README, which I deem important for open source sustainability. 

## Guide-level explanation

- When I generate a new bridgetown site
- A standard README is included in the generated files
- The generated README should be generic, but could include helpful tidbits as well

## Drawbacks

I honestly cannot think of a reason why not to add this.

## Unresolved Questions

What should the README be? It could simple like rails or mildly detailed like ruby gems or it could even implement a builder to personalize for the specific project. That would be a good place to start the discussion.

**Comment by ParamagicDev** [comment]
I agree this should be by here default. Pretty much every project generates a readme, Bridgetown should be no different. I'll come up with something and submit a PR for review.

**Comment by andrewmcodes** [comment]
@ParamagicDev would love to team up on this if you'd like some help! I am a bit of a README connoisseur 😆

**Comment by ParamagicDev** [comment]
@andrewmcodes I see that... I just went through a bunch of your README's. I'd be happy to review whatever you come up with ;)

**Comment by andrewmcodes** [comment]
I unfortunately don't have time to do much better but here is an idea:

https://gist.github.com/andrewmcodes/e4c54c6549dcf90069c50fcb3559971c

Some enhancements to be made for sure, like abstracting the variables and making them dynamic but hopefully it's a start.

I also love a good look through: https://github.com/matiassingers/awesome-readme

**Comment by jaredcwhite** [comment]
Yeah it's certainly not top priority, but I do think it's a nice-to-have. Appreciate the suggested outline!

**Comment by andrewmcodes** [comment]
@jaredcwhite What if we adopt something like https://github.com/RichardLitt/standard-readme 

A simple standard we can base off of would help simplify this while still producing something helpful.
