### ISSUE TITLE
docs: Fix broken reference to master branch

### ISSUE THREAD

**Issue by andrewmcodes** [bridgetownrb/bridgetown#88]
## Motivation

Bugs

## Suggestion

On the [component documentation page](https://www.bridgetownrb.com/docs/components), this link is broken: 

```
https://github.com/bridgetownrb/bridgetown/tree/master/bridgetown-website
```

**Comment by jaredcwhite** [comment]
@andrewmcodes Thanks for the issue! Just pushed up a fix (and found some other similar links which needed correcting).
