### ISSUE TITLE
Creating a Bridgetown 2.0.0 project still creates liquid code

### ISSUE THREAD

**Issue by surrim** [bridgetownrb/bridgetown#904]
When using `bridgetown new mypage` the file `src/posts.md` contains liquid code, `template_engine` is set to `erb`.
Using `bridgetown new mypage -t erb` works fine.

**Bridgetown Version**:
bridgetown 2.0.0.beta1 "(TBD!)"

**To Reproduce**
```shell
bridgetown new mypage # -t erb
cat mypage/src/posts.md
```

**Current behavior**
The file `src/posts.md` contains liquid code.

**Expected behavior**
The file `src/posts.md` should contain erb code.

**Comment by jaredcwhite** [comment]
Thanks for the report, I'll look into it!
