### ISSUE TITLE
Investigate adding Zeitwerk to core gems

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#91]
Because we are pulling in ActiveSupport now, it's bringing the [Zeitwerk gem](https://github.com/fxn/zeitwerk) along for the ride. If we can leverage that to make the process of requiring or autoloading parts of Bridgetown easier and/or faster, that would be groovy.

**Comment by ParamagicDev** [comment]
Based on the current file structure, this shouldnt be too difficult to implement. Based on what I see from the module / file structure of Bridgetown, we may just have to throw in a few `loader.collapse('*/<directory>')`.

IE:

`loader.collapse(''*/concerns") # to avoid making a `Concerns` module.`

[https://github.com/fxn/zeitwerk#collapsing-directories](https://github.com/fxn/zeitwerk#collapsing-directories)
I can take a look into this at some point and see if I can implement it and not break any tests. Ill go ahead and assign myself to this.

**Comment by ParamagicDev** [comment]
@jaredcwhite should we consider explicitly adding `Zeitwerk` Rather than relying on an implicit dependency on the off-chance active-support drops it.

**Comment by jaredcwhite** [comment]
@ParamagicDev Yes. ☺️

**Comment by jaredcwhite** [comment]
This might help streamline some aspects of this:

https://twitter.com/fxn/status/1283166824100761600?s=21
