### ISSUE TITLE
Switch Node/esbuild to ESM default

### ISSUE THREAD

**Issue by jaredcwhite** [bridgetownrb/bridgetown#925]
The current esbuild configuration is using CommonJS rather than ESM (aka `require` rather than `import` statements). To align with the future of Node and the JavaScript ecosystem, we should switch `package.json` and other JS files in new repos over to using ESM.

**Comment by ianbayne** [comment]
Hi @jaredcwhite, is this now closed by https://github.com/bridgetownrb/bridgetown/pull/934/?

**Comment by jaredcwhite** [comment]
@ianbayne Yes indeed!
