### ISSUE TITLE
Liquid Exception: undefined method 'split' for nil:NilClass

### ISSUE THREAD

**Issue by ParamagicDev** [bridgetownrb/bridgetown#93]
Not sure if this should be filed away under docs or bug, but if a webpack loader is unable to load a file correctly (like CSS) it will result in a:

`Liquid Exception: undefined method 'split' for nil:NilClass`

Not sure if we should explain this in the docs, or if we should rescue the Exception and tell the user something went wrong with Webpack.

**Comment by jaredcwhite** [comment]
I'd love to have an explanatory message that helps the user know how they might fix the problem.
