### ISSUE TITLE
feat: add the option to use esbuild

### ISSUE THREAD

**Issue by ParamagicDev** [bridgetownrb/bridgetown#94]
**Update by @jaredcwhite:** focusing on `esbuild` initially, see below…

----

Add a flag to use Snowpack and possibly other bundlers instead of webpack.

`bridgetown new <dir> --bundler=snowpack`

I'm thinking something like the syntax above.

Thoughts?

**Comment by jaredcwhite** [comment]
@ParamagicDev I like the concept…I'm not sure `bundler` by itself is quite the right term, it might be confusing as there's also Ruby Bundler. Maybe `--frontend-bundler` or something like that.

**Comment by jaredcwhite** [comment]
Starting to get excited about Snowpack/Skypack possibilities. Thinking this would be good to prioritize in Q1 2021. Also another opt idea: `--frontend-builder=webpack`, `--frontend-builder=snowpack`

**Comment by ayushn21** [comment]
Given that we have the `--use-postcss` option in `main` now and with the choice of frontend builders soon to come; I wonder if it's worth considering an interactive mode for `bridgetown new`? I know the number of options we have right now is pretty small, but as it gets bigger, it'll likely provide a better developer experience I reckon.

As a developer, I won't have to go through the docs and understsand which options are available to me beforehand. I could just run `bridgetown new` and be asked "How would you like to process your CSS?" and "Which frontend bundler would you like to use?".

I have no idea about the amount of work required for an interactive `new` command though and not completely sure if it's worth it at this point but thought I'd ask the question!!

**Comment by jaredcwhite** [comment]
I have a bit of experience now using esbuild, and with the recent update in Rails 7 to support esbuild specifically, I think it makes sense to focus on that for the time being.
